------------------------------------------------------------------------------ 
formatDialog() - item is Build to Order:  (Len D'Alberti)

{
  "success": "yes",
  "returned_parts": 1,
  "total_count": 1,
  "mfg_count": {
    "REI": 1
  },
  "parts": [
    {
      "_id": "AMDREIAM7969-125JC",
      "part_number": "AM7969-125JC",
      "search_part": "AM7969-125JC|7969 ROHS TAXI RECEIVER AM7969-125JC-G|7969 TAXI RECEIVER AM7969-125JC",
      "manufacturer": "REI",
      "supplier": "AMD",
      "mpq": "0",
      "carrier_type": "",
      "total_qty_for_part": 9999,
      "EuRoHS": null,
      "ChinaRoHS": "",
      "LeadFreeStatus": null,
      "tech_desc": "NULL  NULL",
      "drawing": "",
      "sell_part": "NO",
      "distributor_price": 26.65,
      "prices": {
        "p1_24": 0,
        "p25_99": 0,
        "p100_499": 0,
        "p500_999": 0,
        "over_1000": 0
      },
      "build": 1,
      "se_data": {
        "PartNumber": "AM7969-125JC",
        "Description": "TAXICHIP INTEGRATED CIRCUITS",
        "RoHS": null,
        "Lifecycle": "Aftermarket",
        "ComID": "55150421",
        "ProductLine": "Communication Misc",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2013/12/9/10/13/9/59/re_/manual/re_dscover_am7968_7969.pdf",
        "Family": "",
        "Generic": "",
        "LTBDate": "",
        "CageCode": "3V146",
        "TaxonomyPath": "Communication > Others > Communication Misc",
        "Eccn": "",
        "RadHard": "",
        "Htsusa": "",
        "ScheduleB": "",
        "SubCategory": "Others",
        "LeadFreeStatus": null,
        "EuRoHS": null,
        "ChinaRoHS": null,
        "MaterialDeclaration": null,
        "manufacturerName": "Rochester Electronics",
        "manufacturer": "REI"
      },
      "stock_codes": [
        {
          "stock_code": "BTO81014",
          "long_description": "7969 TAXI RECEIVER AM7969-125JC",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "**",
              "date_code": "9999",
              "notes": "N",
              "qty_available": 0
            }
          ]
        },
        {
          "stock_code": "BTO81015",
          "long_description": "7969 ROHS TAXI RECEIVER AM7969-125JC-G",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "**",
              "date_code": "9999",
              "notes": "N",
              "qty_available": 0
            }
          ]
        }
      ]
    }
  ]
}
------------------------------------------------------------------------------ 