
{
  "success": "yes",
  "total_count": 1,
  "parts": [
    {
      "_id": "ANAANAAD5555CRUZ",
      "part_number": "AD5555CRUZ",
      "search_part": "AD5555CRUZ",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 96,
      "carrier_type": "TUBE",
      "total_qty_for_part": 1074,
      "EuRoHS": "Yes",
      "ChinaRoHS": "Unaffected",
      "LeadFreeStatus": "Compliant",
      "tech_desc": "N/A",
      "drawing": "ROHS",
      "sell_part": "YES",
      "distributor_price": 9.11,
      "prices": {
        "p1_24": 14.02,
        "p25_99": 13.01,
        "p100_499": 12.48,
        "p500_999": 11.99,
        "over_1000": 11.39
      },
      "build": 0,
      "se_data": {
        "PartNumber": "AD5555CRUZ",
        "Description": "DAC 2-CH R-2R/Current Steering 14-bit 16-Pin TSSOP Tube",
        "RoHS": "Yes",
        "Lifecycle": "Active",
        "ComID": "18176336",
        "ProductLine": "DAC",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2014/4/25/22/20/22/203/adi_/manual/2116ad5545_5555.pdf",
        "Family": "AD5555",
        "Generic": "",
        "LTBDate": "",
        "CageCode": "24355",
        "TaxonomyPath": "Data Acquisition > Data Converters > DAC",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Data Converters",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "TSSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Thin Shrink Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "16"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "5"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "4.4"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "1.05(Max)"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.2(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "N/A"
        },
        "Packaging": "Tube",
        "LeadFreeStatus": "Compliant",
        "EuRoHS": "Yes",
        "ChinaRoHS": "Unaffected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/2008/05/07/isys/adi/24994151tssop_4.4_16lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2011/8/7/0/59/58/867/adi_/manual/tssop-16.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "1442113G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 96,
          "carrier_type": "TUBE",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1014",
              "notes": "N",
              "qty_available": 189
            },
            {
              "warehouse": "04",
              "date_code": "1022",
              "notes": "N",
              "qty_available": 214
            },
            {
              "warehouse": "04",
              "date_code": "1051",
              "notes": "N",
              "qty_available": 140
            }
          ]
        },
        {
          "stock_code": "1456404G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 96,
          "carrier_type": "TUBE",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1014",
              "notes": "N",
              "qty_available": 180
            }
          ]
        },
        {
          "stock_code": "1621414",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 96,
          "carrier_type": "TUBE",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1051",
              "notes": "N",
              "qty_available": 38
            }
          ]
        },
        {
          "stock_code": "2083806G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 96,
          "carrier_type": "TUBE",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1244",
              "notes": "N",
              "qty_available": 273
            }
          ]
        },
        {
          "stock_code": "2695175G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 96,
          "carrier_type": "TUBE",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1218",
              "notes": "N",
              "qty_available": 2
            },
            {
              "warehouse": "04",
              "date_code": "1417",
              "notes": "N",
              "qty_available": 38
            }
          ]
        }
      ]
    }
  ]
}
