{
  "success": "yes",
  "total_count": 36,
  "parts": [
    {
      "_id": "HARHAR73333 UM",
      "part_number": "73333 UM",
      "search_part": "73333 UM",
      "manufacturer": "HAR",
      "supplier": "HAR",
      "mpq": "0",
      "carrier_type": "",
      "total_qty_for_part": 486,
      "EuRoHS": "NO",
      "LeadFreeStatus": "NO",
      "ChinaRoHS": "",
      "tech_desc": "N/A",
      "drawing": "N/A",
      "sell_part": "NO",
      "distributor_price": 0,
      "prices": {
        "p1_24": 0,
        "p25_99": 0,
        "p100_499": 0,
        "p500_999": 0,
        "over_1000": 0
      },
      "build": 0,
      "se_data": "",
      "stock_codes": [
        {
          "stock_code": "73333",
          "long_description": "UNMARKED",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "MIXED",
              "notes": "N",
              "qty_available": 486
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARM-1.5-RL7",
      "part_number": "ADP3333ARM-1.5-RL7",
      "search_part": "ADP3333ARM-1.5-RL7",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 1000,
      "carrier_type": "REEL7",
      "total_qty_for_part": 8667,
      "EuRoHS": "No",
      "ChinaRoHS": "Affected",
      "LeadFreeStatus": "Not Compliant",
      "tech_desc": "N/A",
      "drawing": "BROKEN TR",
      "sell_part": "YES",
      "distributor_price": 1.06,
      "prices": {
        "p1_24": 1.63,
        "p25_99": 1.51,
        "p100_499": 1.45,
        "p500_999": 1.39,
        "over_1000": 1.33
      },
      "build": 0,
      "se_data": {
        "PartNumber": "ADP3333ARM-1.5-RL7",
        "Description": "LDO Regulator Pos 1.5V 0.6A 8-Pin MSOP T/R",
        "RoHS": "No",
        "Lifecycle": "Obsolete",
        "ComID": "17347085",
        "ProductLine": "Linear Regulator",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2009/4/22/5/18/8/adi_/auto/adp3333.pdf",
        "Family": "ADP3333",
        "Generic": "",
        "LTBDate": "05/14/2011",
        "CageCode": "24355",
        "TaxonomyPath": "Power Management > Linear Regulators and Controllers > Linear Regulator",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Linear Regulators and Controllers",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "MSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Micro Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "8"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "3"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "0.85"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "Industrial"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Not Compliant",
        "EuRoHS": "No",
        "ChinaRoHS": "Affected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/chemical_data/analog devices/604561085md_msop_3x3_8lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2009/8/12/5/18/25/328/txn_/manual/296-8-msop.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "1090245G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0604",
              "notes": "N",
              "qty_available": 3000
            },
            {
              "warehouse": "04",
              "date_code": "0611",
              "notes": "N",
              "qty_available": 1666
            }
          ]
        },
        {
          "stock_code": "348548",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "0604",
              "notes": "N",
              "qty_available": 1000
            }
          ]
        },
        {
          "stock_code": "705685",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0611",
              "notes": "N",
              "qty_available": 1000
            }
          ]
        },
        {
          "stock_code": "778756G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0141",
              "notes": "N",
              "qty_available": 681
            },
            {
              "warehouse": "04",
              "date_code": "0351",
              "notes": "N",
              "qty_available": 893
            },
            {
              "warehouse": "04",
              "date_code": "0419",
              "notes": "N",
              "qty_available": 427
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARM-1.8-RL",
      "part_number": "ADP3333ARM-1.8-RL",
      "search_part": "ADP3333ARM-1.8-RL",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 3000,
      "carrier_type": "REEL",
      "total_qty_for_part": 30495,
      "EuRoHS": "No",
      "ChinaRoHS": "Affected",
      "LeadFreeStatus": "Not Compliant",
      "tech_desc": "N/A",
      "drawing": "TR 3000",
      "sell_part": "YES",
      "distributor_price": 1.06,
      "prices": {
        "p1_24": 1.63,
        "p25_99": 1.51,
        "p100_499": 1.45,
        "p500_999": 1.39,
        "over_1000": 1.33
      },
      "build": 0,
      "se_data": {
        "PartNumber": "ADP3333ARM-1.8-RL",
        "Description": "LDO Regulator Pos 1.8V 0.6A 8-Pin MSOP T/R",
        "RoHS": "No",
        "Lifecycle": "Obsolete",
        "ComID": "17346677",
        "ProductLine": "Linear Regulator",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2009/4/22/5/18/8/adi_/auto/adp3333.pdf",
        "Family": "ADP3333",
        "Generic": "",
        "LTBDate": "12/17/2009",
        "CageCode": "24355",
        "TaxonomyPath": "Power Management > Linear Regulators and Controllers > Linear Regulator",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Linear Regulators and Controllers",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "MSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Micro Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "8"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "3"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "0.85"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "Industrial"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Not Compliant",
        "EuRoHS": "No",
        "ChinaRoHS": "Affected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/chemical_data/analog devices/604561085md_msop_3x3_8lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2009/8/12/5/18/25/328/txn_/manual/296-8-msop.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "1090241",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 3000,
          "carrier_type": "REEL",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0442",
              "notes": "N",
              "qty_available": 2705
            }
          ]
        },
        {
          "stock_code": "1090242G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 3000,
          "carrier_type": "REEL",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0610",
              "notes": "N",
              "qty_available": 5000
            }
          ]
        },
        {
          "stock_code": "351062",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 3000,
          "carrier_type": "REEL",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "0330",
              "notes": "N",
              "qty_available": 1790
            }
          ]
        },
        {
          "stock_code": "600928G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 3000,
          "carrier_type": "REEL",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0442",
              "notes": "N",
              "qty_available": 21000
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARM-1.8-RL7",
      "part_number": "ADP3333ARM-1.8-RL7",
      "search_part": "ADP3333ARM-1.8-RL7",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 1000,
      "carrier_type": "REEL7",
      "total_qty_for_part": 6001,
      "EuRoHS": "No",
      "ChinaRoHS": "Affected",
      "LeadFreeStatus": "Not Compliant",
      "tech_desc": "N/A",
      "drawing": "BROKEN TR",
      "sell_part": "YES",
      "distributor_price": 1.06,
      "prices": {
        "p1_24": 1.63,
        "p25_99": 1.51,
        "p100_499": 1.45,
        "p500_999": 1.39,
        "over_1000": 1.33
      },
      "build": 0,
      "se_data": {
        "PartNumber": "ADP3333ARM-1.8-RL7",
        "Description": "LDO Regulator Pos 1.8V 0.6A 8-Pin MSOP T/R",
        "RoHS": "No",
        "Lifecycle": "Obsolete",
        "ComID": "17346937",
        "ProductLine": "Linear Regulator",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2009/4/22/5/18/8/adi_/auto/adp3333.pdf",
        "Family": "ADP3333",
        "Generic": "",
        "LTBDate": "12/17/2009",
        "CageCode": "24355",
        "TaxonomyPath": "Power Management > Linear Regulators and Controllers > Linear Regulator",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Linear Regulators and Controllers",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "MSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Micro Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "8"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "3"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "0.85"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "Industrial"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Not Compliant",
        "EuRoHS": "No",
        "ChinaRoHS": "Affected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/chemical_data/analog devices/604561085md_msop_3x3_8lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2009/8/12/5/18/25/328/txn_/manual/296-8-msop.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "1090255G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0629",
              "notes": "N",
              "qty_available": 3000
            }
          ]
        },
        {
          "stock_code": "750143G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0449",
              "notes": "N",
              "qty_available": 3000
            }
          ]
        },
        {
          "stock_code": "778714G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0141",
              "notes": "N",
              "qty_available": 1
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARM-2.5-RL",
      "part_number": "ADP3333ARM-2.5-RL",
      "search_part": "ADP3333ARM-2.5-RL",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 3000,
      "carrier_type": "REEL",
      "total_qty_for_part": 20650,
      "EuRoHS": "No",
      "ChinaRoHS": "Affected",
      "LeadFreeStatus": "Not Compliant",
      "tech_desc": "N/A",
      "drawing": "TR 3000",
      "sell_part": "YES",
      "distributor_price": 1.06,
      "prices": {
        "p1_24": 1.63,
        "p25_99": 1.51,
        "p100_499": 1.45,
        "p500_999": 1.39,
        "over_1000": 1.33
      },
      "build": 0,
      "se_data": {
        "PartNumber": "ADP3333ARM-2.5-RL",
        "Description": "LDO Regulator Pos 2.5V 0.6A 8-Pin MSOP T/R",
        "RoHS": "No",
        "Lifecycle": "Obsolete",
        "ComID": "17348075",
        "ProductLine": "Linear Regulator",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2009/4/22/5/18/8/adi_/auto/adp3333.pdf",
        "Family": "ADP3333",
        "Generic": "",
        "LTBDate": "05/14/2011",
        "CageCode": "24355",
        "TaxonomyPath": "Power Management > Linear Regulators and Controllers > Linear Regulator",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Linear Regulators and Controllers",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "MSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Micro Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "8"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "3"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "0.85"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "Industrial"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Not Compliant",
        "EuRoHS": "No",
        "ChinaRoHS": "Affected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/chemical_data/analog devices/604561085md_msop_3x3_8lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2009/8/12/5/18/25/328/txn_/manual/296-8-msop.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "600916G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 3000,
          "carrier_type": "REEL",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "MIX 04",
              "notes": "N",
              "qty_available": 20650
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARM-2.5-RL7",
      "part_number": "ADP3333ARM-2.5-RL7",
      "search_part": "ADP3333ARM-2.5-RL7",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 1000,
      "carrier_type": "REEL7",
      "total_qty_for_part": 10199,
      "EuRoHS": "No",
      "ChinaRoHS": "Affected",
      "LeadFreeStatus": "Not Compliant",
      "tech_desc": "N/A",
      "drawing": "BROKEN TR",
      "sell_part": "YES",
      "distributor_price": 1.06,
      "prices": {
        "p1_24": 1.63,
        "p25_99": 1.51,
        "p100_499": 1.45,
        "p500_999": 1.39,
        "over_1000": 1.33
      },
      "build": 0,
      "se_data": {
        "PartNumber": "ADP3333ARM-2.5-RL7",
        "Description": "LDO Regulator Pos 2.5V 0.6A 8-Pin MSOP T/R",
        "RoHS": "No",
        "Lifecycle": "Obsolete",
        "ComID": "17346829",
        "ProductLine": "Linear Regulator",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2009/4/22/5/18/8/adi_/auto/adp3333.pdf",
        "Family": "ADP3333",
        "Generic": "",
        "LTBDate": "05/14/2011",
        "CageCode": "24355",
        "TaxonomyPath": "Power Management > Linear Regulators and Controllers > Linear Regulator",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Linear Regulators and Controllers",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "MSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Micro Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "8"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "3"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "0.85"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "Industrial"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Not Compliant",
        "EuRoHS": "No",
        "ChinaRoHS": "Affected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/chemical_data/analog devices/604561085md_msop_3x3_8lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2009/8/12/5/18/25/328/txn_/manual/296-8-msop.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "1271819G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0721",
              "notes": "N",
              "qty_available": 4400
            },
            {
              "warehouse": "04",
              "date_code": "MIX 07",
              "notes": "N",
              "qty_available": 4000
            }
          ]
        },
        {
          "stock_code": "748507",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0417",
              "notes": "N",
              "qty_available": 1000
            }
          ]
        },
        {
          "stock_code": "778710G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0141",
              "notes": "N",
              "qty_available": 1
            },
            {
              "warehouse": "04",
              "date_code": "0404",
              "notes": "N",
              "qty_available": 762
            }
          ]
        },
        {
          "stock_code": "813712",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0510",
              "notes": "N",
              "qty_available": 36
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARM-2.77-R7",
      "part_number": "ADP3333ARM-2.77-R7",
      "search_part": "ADP3333ARM-2.77-R7",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 1000,
      "carrier_type": "REEL7",
      "total_qty_for_part": 7494,
      "EuRoHS": "No",
      "ChinaRoHS": "Affected",
      "LeadFreeStatus": "Not Compliant",
      "tech_desc": "N/A",
      "drawing": "BROKEN TR",
      "sell_part": "YES",
      "distributor_price": 1.06,
      "prices": {
        "p1_24": 1.63,
        "p25_99": 1.51,
        "p100_499": 1.45,
        "p500_999": 1.39,
        "over_1000": 1.33
      },
      "build": 0,
      "se_data": {
        "PartNumber": "ADP3333ARM-2.77-R7",
        "Description": "LDO Regulator Pos 2.77V 0.6A 8-Pin MSOP T/R",
        "RoHS": "No",
        "Lifecycle": "Obsolete",
        "ComID": "17346602",
        "ProductLine": "Linear Regulator",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2009/4/22/5/18/8/adi_/auto/adp3333.pdf",
        "Family": "ADP3333",
        "Generic": "",
        "LTBDate": "12/17/2009",
        "CageCode": "24355",
        "TaxonomyPath": "Power Management > Linear Regulators and Controllers > Linear Regulator",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Linear Regulators and Controllers",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "MSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Micro Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "8"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "3"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "0.85"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "Industrial"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Not Compliant",
        "EuRoHS": "No",
        "ChinaRoHS": "Affected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/chemical_data/analog devices/604561085md_msop_3x3_8lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2009/8/12/5/18/25/328/txn_/manual/296-8-msop.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "296988",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "0141",
              "notes": "N",
              "qty_available": 1000
            }
          ]
        },
        {
          "stock_code": "538537G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0422",
              "notes": "N",
              "qty_available": 4000
            }
          ]
        },
        {
          "stock_code": "791338G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0141",
              "notes": "N",
              "qty_available": 970
            },
            {
              "warehouse": "04",
              "date_code": "0405",
              "notes": "N",
              "qty_available": 806
            }
          ]
        },
        {
          "stock_code": "791341",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0422",
              "notes": "N",
              "qty_available": 543
            }
          ]
        },
        {
          "stock_code": "813735",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0141",
              "notes": "N",
              "qty_available": 175
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARM-3-R7",
      "part_number": "ADP3333ARM-3-R7",
      "search_part": "ADP3333ARM-3-R7",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": "0",
      "carrier_type": "",
      "total_qty_for_part": 14,
      "EuRoHS": "NO",
      "LeadFreeStatus": "NO",
      "ChinaRoHS": "",
      "tech_desc": "N/A",
      "drawing": "BROKEN TR",
      "sell_part": "NO",
      "distributor_price": 0,
      "prices": {
        "p1_24": 0,
        "p25_99": 0,
        "p100_499": 0,
        "p500_999": 0,
        "over_1000": 0
      },
      "build": 0,
      "se_data": "",
      "stock_codes": [
        {
          "stock_code": "813815",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0415",
              "notes": "N",
              "qty_available": 14
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARM-3-REEL7",
      "part_number": "ADP3333ARM-3-REEL7",
      "search_part": "ADP3333ARM-3-REEL7",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 1000,
      "carrier_type": "REEL7",
      "total_qty_for_part": 4117,
      "EuRoHS": "No",
      "ChinaRoHS": "Affected",
      "LeadFreeStatus": "Not Compliant",
      "tech_desc": "N/A",
      "drawing": "BROKEN TR",
      "sell_part": "YES",
      "distributor_price": 1.06,
      "prices": {
        "p1_24": 1.63,
        "p25_99": 1.51,
        "p100_499": 1.45,
        "p500_999": 1.39,
        "over_1000": 1.33
      },
      "build": 0,
      "se_data": {
        "PartNumber": "ADP3333ARM-3-REEL7",
        "Description": "LDO Regulator Pos 3V 0.6A 8-Pin MSOP T/R",
        "RoHS": "No",
        "Lifecycle": "Obsolete",
        "ComID": "17411020",
        "ProductLine": "Linear Regulator",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2009/4/22/5/18/8/adi_/auto/adp3333.pdf",
        "Family": "ADP3333",
        "Generic": "",
        "LTBDate": "05/14/2011",
        "CageCode": "24355",
        "TaxonomyPath": "Power Management > Linear Regulators and Controllers > Linear Regulator",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Linear Regulators and Controllers",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "MSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Micro Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "8"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "3"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "0.85"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "Industrial"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Not Compliant",
        "EuRoHS": "No",
        "ChinaRoHS": "Affected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/chemical_data/analog devices/604561085md_msop_3x3_8lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2009/8/12/5/18/25/328/txn_/manual/296-8-msop.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "1331770G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0801",
              "notes": "N",
              "qty_available": 3000
            }
          ]
        },
        {
          "stock_code": "296986",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "0141",
              "notes": "N",
              "qty_available": 1000
            }
          ]
        },
        {
          "stock_code": "813744",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0141",
              "notes": "N",
              "qty_available": 117
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARM-3.15-R7",
      "part_number": "ADP3333ARM-3.15-R7",
      "search_part": "ADP3333ARM-3.15-R7",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 1000,
      "carrier_type": "REEL7",
      "total_qty_for_part": 35326,
      "EuRoHS": "No",
      "ChinaRoHS": "Affected",
      "LeadFreeStatus": "Not Compliant",
      "tech_desc": "N/A",
      "drawing": "BROKEN TR",
      "sell_part": "YES",
      "distributor_price": 1.06,
      "prices": {
        "p1_24": 1.63,
        "p25_99": 1.51,
        "p100_499": 1.45,
        "p500_999": 1.39,
        "over_1000": 1.33
      },
      "build": 0,
      "se_data": {
        "PartNumber": "ADP3333ARM-3.15-R7",
        "Description": "LDO Regulator Pos 3.15V 0.6A 8-Pin MSOP T/R",
        "RoHS": "No",
        "Lifecycle": "Obsolete",
        "ComID": "17346926",
        "ProductLine": "Linear Regulator",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2009/4/22/5/18/8/adi_/auto/adp3333.pdf",
        "Family": "ADP3333",
        "Generic": "",
        "LTBDate": "05/14/2011",
        "CageCode": "24355",
        "TaxonomyPath": "Power Management > Linear Regulators and Controllers > Linear Regulator",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Linear Regulators and Controllers",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "MSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Micro Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "8"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "3"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "0.85"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "Industrial"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Not Compliant",
        "EuRoHS": "No",
        "ChinaRoHS": "Affected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/chemical_data/analog devices/604561085md_msop_3x3_8lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2009/8/12/5/18/25/328/txn_/manual/296-8-msop.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "1285208G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "MIX 07",
              "notes": "N",
              "qty_available": 5000
            }
          ]
        },
        {
          "stock_code": "237905G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "MIX 03",
              "notes": "N",
              "qty_available": 16900
            }
          ]
        },
        {
          "stock_code": "275960G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "0314",
              "notes": "N",
              "qty_available": 12813
            }
          ]
        },
        {
          "stock_code": "791418",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0131",
              "notes": "N",
              "qty_available": 164
            }
          ]
        },
        {
          "stock_code": "813749",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0131",
              "notes": "N",
              "qty_available": 449
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARM-3.15-RL",
      "part_number": "ADP3333ARM-3.15-RL",
      "search_part": "ADP3333ARM-3.15-RL",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 3000,
      "carrier_type": "REEL",
      "total_qty_for_part": 9000,
      "EuRoHS": "No",
      "ChinaRoHS": "Affected",
      "LeadFreeStatus": "Not Compliant",
      "tech_desc": "N/A",
      "drawing": "TR 3000",
      "sell_part": "YES",
      "distributor_price": 1.06,
      "prices": {
        "p1_24": 1.63,
        "p25_99": 1.51,
        "p100_499": 1.45,
        "p500_999": 1.39,
        "over_1000": 1.33
      },
      "build": 0,
      "se_data": {
        "PartNumber": "ADP3333ARM-3.15-RL",
        "Description": "LDO Regulator Pos 3.15V 0.6A 8-Pin MSOP T/R",
        "RoHS": "No",
        "Lifecycle": "Obsolete",
        "ComID": "17348425",
        "ProductLine": "Linear Regulator",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2009/4/22/5/18/8/adi_/auto/adp3333.pdf",
        "Family": "ADP3333",
        "Generic": "",
        "LTBDate": "05/14/2011",
        "CageCode": "24355",
        "TaxonomyPath": "Power Management > Linear Regulators and Controllers > Linear Regulator",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Linear Regulators and Controllers",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "MSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Micro Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "8"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "3"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "0.85"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "Industrial"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Not Compliant",
        "EuRoHS": "No",
        "ChinaRoHS": "Affected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/chemical_data/analog devices/604561085md_msop_3x3_8lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2009/8/12/5/18/25/328/txn_/manual/296-8-msop.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "1328404",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 3000,
          "carrier_type": "REEL",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0736",
              "notes": "N",
              "qty_available": 3000
            }
          ]
        },
        {
          "stock_code": "237901G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 3000,
          "carrier_type": "REEL",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "0244",
              "notes": "N",
              "qty_available": 6000
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARM-3.3-RL",
      "part_number": "ADP3333ARM-3.3-RL",
      "search_part": "ADP3333ARM-3.3-RL",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 3000,
      "carrier_type": "REEL",
      "total_qty_for_part": 4776,
      "EuRoHS": "No",
      "ChinaRoHS": "Affected",
      "LeadFreeStatus": "Not Compliant",
      "tech_desc": "N/A",
      "drawing": "TR 3K",
      "sell_part": "YES",
      "distributor_price": 2.06,
      "prices": {
        "p1_24": 3.17,
        "p25_99": 2.94,
        "p100_499": 2.82,
        "p500_999": 2.71,
        "over_1000": 2.58
      },
      "build": 0,
      "se_data": {
        "PartNumber": "ADP3333ARM-3.3-RL",
        "Description": "LDO Regulator Pos 3.3V 0.6A 8-Pin MSOP T/R",
        "RoHS": "No",
        "Lifecycle": "Obsolete",
        "ComID": "17348477",
        "ProductLine": "Linear Regulator",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2009/4/22/5/18/8/adi_/auto/adp3333.pdf",
        "Family": "ADP3333",
        "Generic": "",
        "LTBDate": "12/17/2009",
        "CageCode": "24355",
        "TaxonomyPath": "Power Management > Linear Regulators and Controllers > Linear Regulator",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Linear Regulators and Controllers",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "MSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Micro Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "8"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "3"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "0.85"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "Industrial"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Not Compliant",
        "EuRoHS": "No",
        "ChinaRoHS": "Affected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/chemical_data/analog devices/604561085md_msop_3x3_8lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2009/8/12/5/18/25/328/txn_/manual/296-8-msop.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "1535121",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 3000,
          "carrier_type": "REEL",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0747",
              "notes": "N",
              "qty_available": 3000
            }
          ]
        },
        {
          "stock_code": "538532",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 3000,
          "carrier_type": "REEL",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0418",
              "notes": "N",
              "qty_available": 1776
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARM-3.3-RL7",
      "part_number": "ADP3333ARM-3.3-RL7",
      "search_part": "ADP3333ARM-3.3-RL7",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 1000,
      "carrier_type": "REEL7",
      "total_qty_for_part": 4762,
      "EuRoHS": "No",
      "ChinaRoHS": "Affected",
      "LeadFreeStatus": "Not Compliant",
      "tech_desc": "N/A",
      "drawing": "TR QTY 1000",
      "sell_part": "YES",
      "distributor_price": 1.06,
      "prices": {
        "p1_24": 1.63,
        "p25_99": 1.51,
        "p100_499": 1.45,
        "p500_999": 1.39,
        "over_1000": 1.33
      },
      "build": 0,
      "se_data": {
        "PartNumber": "ADP3333ARM-3.3-RL7",
        "Description": "LDO Regulator Pos 3.3V 0.6A 8-Pin MSOP T/R",
        "RoHS": "No",
        "Lifecycle": "Active",
        "ComID": "17348287",
        "ProductLine": "Linear Regulator",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2009/4/22/5/18/8/adi_/auto/adp3333.pdf",
        "Family": "ADP3333",
        "Generic": "",
        "LTBDate": "",
        "CageCode": "24355",
        "TaxonomyPath": "Power Management > Linear Regulators and Controllers > Linear Regulator",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Linear Regulators and Controllers",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "MSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Micro Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "8"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "3"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "0.85"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "Industrial"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Not Compliant",
        "EuRoHS": "No",
        "ChinaRoHS": "Affected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/chemical_data/analog devices/604561085md_msop_3x3_8lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2009/8/12/5/18/25/328/txn_/manual/296-8-msop.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "1105011G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0940",
              "notes": "N",
              "qty_available": 2000
            }
          ]
        },
        {
          "stock_code": "1331768",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0743",
              "notes": "N",
              "qty_available": 762
            }
          ]
        },
        {
          "stock_code": "2449465G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1004",
              "notes": "N",
              "qty_available": 2000
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARM-3.3-RL7  REEL",
      "part_number": "ADP3333ARM-3.3-RL7  REEL",
      "search_part": "ADP3333ARM-3.3-RL7  REEL",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": "0",
      "carrier_type": "",
      "total_qty_for_part": 316,
      "EuRoHS": "NO",
      "LeadFreeStatus": "NO",
      "ChinaRoHS": "",
      "tech_desc": "N/A",
      "drawing": "TR-316",
      "sell_part": "YES",
      "distributor_price": 1.06,
      "prices": {
        "p1_24": 1.63,
        "p25_99": 1.51,
        "p100_499": 1.45,
        "p500_999": 1.39,
        "over_1000": 1.33
      },
      "build": 0,
      "se_data": "",
      "stock_codes": [
        {
          "stock_code": "1288864",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "0743",
              "notes": "N",
              "qty_available": 316
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARM-5-REEL",
      "part_number": "ADP3333ARM-5-REEL",
      "search_part": "ADP3333ARM-5-REEL",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 3000,
      "carrier_type": "REEL",
      "total_qty_for_part": 5548,
      "EuRoHS": "No",
      "ChinaRoHS": "Affected",
      "LeadFreeStatus": "Not Compliant",
      "tech_desc": "N/A",
      "drawing": "TR QTY 3000",
      "sell_part": "YES",
      "distributor_price": 1.06,
      "prices": {
        "p1_24": 1.63,
        "p25_99": 1.51,
        "p100_499": 1.45,
        "p500_999": 1.39,
        "over_1000": 1.33
      },
      "build": 0,
      "se_data": {
        "PartNumber": "ADP3333ARM-5-REEL",
        "Description": "LDO Regulator Pos 5V 0.6A 8-Pin MSOP T/R",
        "RoHS": "No",
        "Lifecycle": "Obsolete",
        "ComID": "17412549",
        "ProductLine": "Linear Regulator",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2009/4/22/5/18/8/adi_/auto/adp3333.pdf",
        "Family": "ADP3333",
        "Generic": "",
        "LTBDate": "12/17/2009",
        "CageCode": "24355",
        "TaxonomyPath": "Power Management > Linear Regulators and Controllers > Linear Regulator",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Linear Regulators and Controllers",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "MSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Micro Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "8"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "3"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "0.85"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "Industrial"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Not Compliant",
        "EuRoHS": "No",
        "ChinaRoHS": "Affected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/chemical_data/analog devices/604561085md_msop_3x3_8lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2009/8/12/5/18/25/328/txn_/manual/296-8-msop.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "1273329G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 3000,
          "carrier_type": "REEL",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0722",
              "notes": "N",
              "qty_available": 5548
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARM-5-REEL7",
      "part_number": "ADP3333ARM-5-REEL7",
      "search_part": "ADP3333ARM-5-REEL7",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 1000,
      "carrier_type": "REEL7",
      "total_qty_for_part": 3010,
      "EuRoHS": "No",
      "ChinaRoHS": "Affected",
      "LeadFreeStatus": "Not Compliant",
      "tech_desc": "N/A",
      "drawing": "TR 1000",
      "sell_part": "YES",
      "distributor_price": 1.06,
      "prices": {
        "p1_24": 1.63,
        "p25_99": 1.51,
        "p100_499": 1.45,
        "p500_999": 1.39,
        "over_1000": 1.33
      },
      "build": 0,
      "se_data": {
        "PartNumber": "ADP3333ARM-5-REEL7",
        "Description": "LDO Regulator Pos 5V 0.6A 8-Pin MSOP T/R",
        "RoHS": "No",
        "Lifecycle": "Obsolete",
        "ComID": "17411025",
        "ProductLine": "Linear Regulator",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2009/4/22/5/18/8/adi_/auto/adp3333.pdf",
        "Family": "ADP3333",
        "Generic": "",
        "LTBDate": "05/14/2011",
        "CageCode": "24355",
        "TaxonomyPath": "Power Management > Linear Regulators and Controllers > Linear Regulator",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Linear Regulators and Controllers",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "MSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Micro Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "8"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "3"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "0.85"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "Industrial"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Not Compliant",
        "EuRoHS": "No",
        "ChinaRoHS": "Affected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/chemical_data/analog devices/604561085md_msop_3x3_8lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2009/8/12/5/18/25/328/txn_/manual/296-8-msop.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "778737G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0141",
              "notes": "N",
              "qty_available": 786
            },
            {
              "warehouse": "04",
              "date_code": "0240",
              "notes": "N",
              "qty_available": 485
            }
          ]
        },
        {
          "stock_code": "988327",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0141",
              "notes": "N",
              "qty_available": 739
            }
          ]
        },
        {
          "stock_code": "988329",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0141",
              "notes": "N",
              "qty_available": 1000
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARMZ-1.5-R7",
      "part_number": "ADP3333ARMZ-1.5-R7",
      "search_part": "ADP3333ARMZ-1.5-R7",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 1000,
      "carrier_type": "REEL7",
      "total_qty_for_part": 3765,
      "EuRoHS": "Yes",
      "ChinaRoHS": "Unaffected",
      "LeadFreeStatus": "Compliant",
      "tech_desc": "N/A",
      "drawing": "TR QTY 1000 LF ROHS",
      "sell_part": "YES",
      "distributor_price": 0.83,
      "prices": {
        "p1_24": 1.28,
        "p25_99": 1.19,
        "p100_499": 1.14,
        "p500_999": 1.09,
        "over_1000": 1.04
      },
      "build": 0,
      "se_data": {
        "PartNumber": "ADP3333ARMZ-1.5-R7",
        "Description": "LDO Regulator Pos 1.5V 0.6A 8-Pin MSOP T/R",
        "RoHS": "Yes",
        "Lifecycle": "Obsolete",
        "ComID": "19977570",
        "ProductLine": "Linear Regulator",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2009/4/22/5/18/8/adi_/auto/adp3333.pdf",
        "Family": "ADP3333",
        "Generic": "",
        "LTBDate": "05/14/2011",
        "CageCode": "24355",
        "TaxonomyPath": "Power Management > Linear Regulators and Controllers > Linear Regulator",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Linear Regulators and Controllers",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "MSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Micro Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "8"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "3"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "0.85"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "Industrial"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Compliant",
        "EuRoHS": "Yes",
        "ChinaRoHS": "Unaffected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/chemical_data/analog devices/604561085md_msop_3x3_8lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2009/8/12/5/18/25/328/txn_/manual/296-8-msop.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "1096536",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0611",
              "notes": "N",
              "qty_available": 889
            }
          ]
        },
        {
          "stock_code": "1458981",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0752",
              "notes": "N",
              "qty_available": 876
            }
          ]
        },
        {
          "stock_code": "2296482G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1032",
              "notes": "N",
              "qty_available": 2000
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARMZ-1.5-RL",
      "part_number": "ADP3333ARMZ-1.5-RL",
      "search_part": "ADP3333ARMZ-1.5-RL",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 3000,
      "carrier_type": "REEL",
      "total_qty_for_part": 2960,
      "EuRoHS": "Yes",
      "ChinaRoHS": "Unaffected",
      "LeadFreeStatus": "Compliant",
      "tech_desc": "N/A",
      "drawing": "BROKEN TR DP LF ROHS",
      "sell_part": "YES",
      "distributor_price": 0.83,
      "prices": {
        "p1_24": 1.28,
        "p25_99": 1.19,
        "p100_499": 1.14,
        "p500_999": 1.09,
        "over_1000": 1.04
      },
      "build": 0,
      "se_data": {
        "PartNumber": "ADP3333ARMZ-1.5-RL",
        "Description": "LDO Regulator Pos 1.5V 0.6A 8-Pin MSOP T/R",
        "RoHS": "Yes",
        "Lifecycle": "Active",
        "ComID": "19977635",
        "ProductLine": "Linear Regulator",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2009/4/22/5/18/8/adi_/auto/adp3333.pdf",
        "Family": "ADP3333",
        "Generic": "",
        "LTBDate": "",
        "CageCode": "24355",
        "TaxonomyPath": "Power Management > Linear Regulators and Controllers > Linear Regulator",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Linear Regulators and Controllers",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "MSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Micro Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "8"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "3"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "0.85"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "Industrial"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Compliant",
        "EuRoHS": "Yes",
        "ChinaRoHS": "Unaffected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/chemical_data/analog devices/604561085md_msop_3x3_8lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2009/8/12/5/18/25/328/txn_/manual/296-8-msop.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "2296329",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 3000,
          "carrier_type": "REEL",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1122",
              "notes": "N",
              "qty_available": 2960
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARMZ-1.8RL7",
      "part_number": "ADP3333ARMZ-1.8RL7",
      "search_part": "ADP3333ARMZ-1.8RL7",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 1000,
      "carrier_type": "REEL7",
      "total_qty_for_part": 15843,
      "EuRoHS": "Yes",
      "ChinaRoHS": "Unaffected",
      "LeadFreeStatus": "Compliant",
      "tech_desc": "N/A",
      "drawing": "BROKEN TR LF",
      "sell_part": "YES",
      "distributor_price": 0.83,
      "prices": {
        "p1_24": 1.28,
        "p25_99": 1.19,
        "p100_499": 1.14,
        "p500_999": 1.09,
        "over_1000": 1.04
      },
      "build": 0,
      "se_data": {
        "PartNumber": "ADP3333ARMZ-1.8RL7",
        "Description": "LDO Regulator Pos 1.8V 0.6A 8-Pin MSOP T/R",
        "RoHS": "Yes",
        "Lifecycle": "Active",
        "ComID": "19977611",
        "ProductLine": "Linear Regulator",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2009/4/22/5/18/8/adi_/auto/adp3333.pdf",
        "Family": "ADP3333",
        "Generic": "",
        "LTBDate": "",
        "CageCode": "24355",
        "TaxonomyPath": "Power Management > Linear Regulators and Controllers > Linear Regulator",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Linear Regulators and Controllers",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "MSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Micro Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "8"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "3"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "0.85"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "Industrial"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Compliant",
        "EuRoHS": "Yes",
        "ChinaRoHS": "Unaffected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/chemical_data/analog devices/604561085md_msop_3x3_8lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2009/8/12/5/18/25/328/txn_/manual/296-8-msop.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "1197063",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0650",
              "notes": "N",
              "qty_available": 192
            }
          ]
        },
        {
          "stock_code": "1456930",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "MIX 08",
              "notes": "N",
              "qty_available": 259
            }
          ]
        },
        {
          "stock_code": "1481165G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0941",
              "notes": "N",
              "qty_available": 1000
            },
            {
              "warehouse": "04",
              "date_code": "MIX09",
              "notes": "N",
              "qty_available": 1000
            }
          ]
        },
        {
          "stock_code": "1592206G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0845",
              "notes": "N",
              "qty_available": 289
            },
            {
              "warehouse": "04",
              "date_code": "0908",
              "notes": "N",
              "qty_available": 690
            }
          ]
        },
        {
          "stock_code": "1604338G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "MIX09+",
              "notes": "N",
              "qty_available": 2000
            }
          ]
        },
        {
          "stock_code": "1763420G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0923",
              "notes": "N",
              "qty_available": 989
            },
            {
              "warehouse": "04",
              "date_code": "0931",
              "notes": "N",
              "qty_available": 415
            }
          ]
        },
        {
          "stock_code": "1763784",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "MIX 09",
              "notes": "N",
              "qty_available": 89
            }
          ]
        },
        {
          "stock_code": "1829587",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1001",
              "notes": "N",
              "qty_available": 863
            }
          ]
        },
        {
          "stock_code": "1915381",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "MIX 10",
              "notes": "N",
              "qty_available": 118
            }
          ]
        },
        {
          "stock_code": "1977043",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1028",
              "notes": "N",
              "qty_available": 517
            }
          ]
        },
        {
          "stock_code": "2017933",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1042",
              "notes": "N",
              "qty_available": 595
            }
          ]
        },
        {
          "stock_code": "2126213",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1213",
              "notes": "N",
              "qty_available": 1000
            }
          ]
        },
        {
          "stock_code": "2282629",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1111",
              "notes": "N",
              "qty_available": 570
            }
          ]
        },
        {
          "stock_code": "2282630",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1114",
              "notes": "N",
              "qty_available": 369
            }
          ]
        },
        {
          "stock_code": "2284570",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "MIX 11",
              "notes": "N",
              "qty_available": 274
            }
          ]
        },
        {
          "stock_code": "2607703",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1205",
              "notes": "N",
              "qty_available": 598
            }
          ]
        },
        {
          "stock_code": "2680432G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1312",
              "notes": "N",
              "qty_available": 4000
            }
          ]
        },
        {
          "stock_code": "778718",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0429",
              "notes": "N",
              "qty_available": 16
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARMZ-2.5-R7",
      "part_number": "ADP3333ARMZ-2.5-R7",
      "search_part": "ADP3333ARMZ-2.5-R7",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 1000,
      "carrier_type": "REEL7",
      "total_qty_for_part": 3545,
      "EuRoHS": "Yes",
      "ChinaRoHS": "Unaffected",
      "LeadFreeStatus": "Compliant",
      "tech_desc": "N/A",
      "drawing": "BROKEN TR DP ROHS",
      "sell_part": "YES",
      "distributor_price": 0.83,
      "prices": {
        "p1_24": 1.28,
        "p25_99": 1.19,
        "p100_499": 1.14,
        "p500_999": 1.09,
        "over_1000": 1.04
      },
      "build": 0,
      "se_data": {
        "PartNumber": "ADP3333ARMZ-2.5-R7",
        "Description": "LDO Regulator Pos 2.5V 0.6A 8-Pin MSOP T/R",
        "RoHS": "Yes",
        "Lifecycle": "Active",
        "ComID": "20110872",
        "ProductLine": "Linear Regulator",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2009/4/22/5/18/8/adi_/auto/adp3333.pdf",
        "Family": "ADP3333",
        "Generic": "",
        "LTBDate": "",
        "CageCode": "24355",
        "TaxonomyPath": "Power Management > Linear Regulators and Controllers > Linear Regulator",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Linear Regulators and Controllers",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "MSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Micro Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "8"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "3"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "0.85"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "Industrial"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Compliant",
        "EuRoHS": "Yes",
        "ChinaRoHS": "Unaffected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/chemical_data/analog devices/604561085md_msop_3x3_8lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2009/8/12/5/18/25/328/txn_/manual/296-8-msop.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "1108526",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0445",
              "notes": "N",
              "qty_available": 2765
            }
          ]
        },
        {
          "stock_code": "1535952G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0839",
              "notes": "N",
              "qty_available": 97
            }
          ]
        },
        {
          "stock_code": "2284489",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1114",
              "notes": "N",
              "qty_available": 683
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARMZ-2.5-RL",
      "part_number": "ADP3333ARMZ-2.5-RL",
      "search_part": "ADP3333ARMZ-2.5-RL",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 3000,
      "carrier_type": "REEL",
      "total_qty_for_part": 4377,
      "EuRoHS": "Yes",
      "ChinaRoHS": "Unaffected",
      "LeadFreeStatus": "Compliant",
      "tech_desc": "N/A",
      "drawing": "BROKEN TR LF ROHS",
      "sell_part": "YES",
      "distributor_price": 0.83,
      "prices": {
        "p1_24": 1.28,
        "p25_99": 1.19,
        "p100_499": 1.14,
        "p500_999": 1.09,
        "over_1000": 1.04
      },
      "build": 0,
      "se_data": {
        "PartNumber": "ADP3333ARMZ-2.5-RL",
        "Description": "LDO Regulator Pos 2.5V 0.6A 8-Pin MSOP T/R",
        "RoHS": "Yes",
        "Lifecycle": "Obsolete",
        "ComID": "19977617",
        "ProductLine": "Linear Regulator",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2009/4/22/5/18/8/adi_/auto/adp3333.pdf",
        "Family": "ADP3333",
        "Generic": "",
        "LTBDate": "05/14/2011",
        "CageCode": "24355",
        "TaxonomyPath": "Power Management > Linear Regulators and Controllers > Linear Regulator",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Linear Regulators and Controllers",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "MSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Micro Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "8"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "3"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "0.85"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "Industrial"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Compliant",
        "EuRoHS": "Yes",
        "ChinaRoHS": "Unaffected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/chemical_data/analog devices/604561085md_msop_3x3_8lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2009/8/12/5/18/25/328/txn_/manual/296-8-msop.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "1456973G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 3000,
          "carrier_type": "REEL",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0747",
              "notes": "N",
              "qty_available": 4377
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARMZ-2.77R7",
      "part_number": "ADP3333ARMZ-2.77R7",
      "search_part": "ADP3333ARMZ-2.77R7",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 1000,
      "carrier_type": "REEL7",
      "total_qty_for_part": 5860,
      "EuRoHS": "Yes",
      "ChinaRoHS": "Unaffected",
      "LeadFreeStatus": "Compliant",
      "tech_desc": "N/A",
      "drawing": "BROKEN TR LF ROHS",
      "sell_part": "YES",
      "distributor_price": 0.83,
      "prices": {
        "p1_24": 1.28,
        "p25_99": 1.19,
        "p100_499": 1.14,
        "p500_999": 1.09,
        "over_1000": 1.04
      },
      "build": 0,
      "se_data": {
        "PartNumber": "ADP3333ARMZ-2.77R7",
        "Description": "LDO Regulator Pos 2.77V 0.6A 8-Pin MSOP T/R",
        "RoHS": "Yes",
        "Lifecycle": "Active",
        "ComID": "20110868",
        "ProductLine": "Linear Regulator",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2009/4/22/5/18/8/adi_/auto/adp3333.pdf",
        "Family": "ADP3333",
        "Generic": "",
        "LTBDate": "",
        "CageCode": "24355",
        "TaxonomyPath": "Power Management > Linear Regulators and Controllers > Linear Regulator",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Linear Regulators and Controllers",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "MSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Micro Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "8"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "3"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "0.85"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "Industrial"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Compliant",
        "EuRoHS": "Yes",
        "ChinaRoHS": "Unaffected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/chemical_data/analog devices/604561085md_msop_3x3_8lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2009/8/12/5/18/25/328/txn_/manual/296-8-msop.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "1227447G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0541",
              "notes": "N",
              "qty_available": 4000
            }
          ]
        },
        {
          "stock_code": "2017806",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1040",
              "notes": "N",
              "qty_available": 980
            }
          ]
        },
        {
          "stock_code": "778719",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0541",
              "notes": "N",
              "qty_available": 880
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARMZ-3-R7",
      "part_number": "ADP3333ARMZ-3-R7",
      "search_part": "ADP3333ARMZ-3-R7",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 1000,
      "carrier_type": "REEL7",
      "total_qty_for_part": 1951,
      "EuRoHS": "Yes",
      "ChinaRoHS": "Unaffected",
      "LeadFreeStatus": "Compliant",
      "tech_desc": "N/A",
      "drawing": "BROKEN TR LF ROHS",
      "sell_part": "YES",
      "distributor_price": 0.83,
      "prices": {
        "p1_24": 1.28,
        "p25_99": 1.19,
        "p100_499": 1.14,
        "p500_999": 1.09,
        "over_1000": 1.04
      },
      "build": 0,
      "se_data": {
        "PartNumber": "ADP3333ARMZ-3-R7",
        "Description": "LDO Regulator Pos 3V 0.6A 8-Pin MSOP T/R",
        "RoHS": "Yes",
        "Lifecycle": "Active",
        "ComID": "19977615",
        "ProductLine": "Linear Regulator",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2009/4/22/5/18/8/adi_/auto/adp3333.pdf",
        "Family": "ADP3333",
        "Generic": "",
        "LTBDate": "",
        "CageCode": "24355",
        "TaxonomyPath": "Power Management > Linear Regulators and Controllers > Linear Regulator",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Linear Regulators and Controllers",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "MSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Micro Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "8"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "3"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "0.85"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "Industrial"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Compliant",
        "EuRoHS": "Yes",
        "ChinaRoHS": "Unaffected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/chemical_data/analog devices/604561085md_msop_3x3_8lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2009/8/12/5/18/25/328/txn_/manual/296-8-msop.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "1590319",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0827",
              "notes": "N",
              "qty_available": 427
            }
          ]
        },
        {
          "stock_code": "1829565",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "MIX 09+",
              "notes": "N",
              "qty_available": 489
            }
          ]
        },
        {
          "stock_code": "2018006",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1030",
              "notes": "N",
              "qty_available": 649
            }
          ]
        },
        {
          "stock_code": "932162",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0608",
              "notes": "N",
              "qty_available": 386
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARMZ-3.15R7",
      "part_number": "ADP3333ARMZ-3.15R7",
      "search_part": "ADP3333ARMZ-3.15R7",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 1000,
      "carrier_type": "REEL7",
      "total_qty_for_part": 5104,
      "EuRoHS": "Yes",
      "ChinaRoHS": "Unaffected",
      "LeadFreeStatus": "Compliant",
      "tech_desc": "N/A",
      "drawing": "BROKEN TR DP ROHS",
      "sell_part": "YES",
      "distributor_price": 0.83,
      "prices": {
        "p1_24": 1.28,
        "p25_99": 1.19,
        "p100_499": 1.14,
        "p500_999": 1.09,
        "over_1000": 1.04
      },
      "build": 0,
      "se_data": {
        "PartNumber": "ADP3333ARMZ-3.15R7",
        "Description": "LDO Regulator Pos 3.15V 0.6A 8-Pin MSOP T/R",
        "RoHS": "Yes",
        "Lifecycle": "Active",
        "ComID": "19977607",
        "ProductLine": "Linear Regulator",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2009/4/22/5/18/8/adi_/auto/adp3333.pdf",
        "Family": "ADP3333",
        "Generic": "",
        "LTBDate": "",
        "CageCode": "24355",
        "TaxonomyPath": "Power Management > Linear Regulators and Controllers > Linear Regulator",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Linear Regulators and Controllers",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "MSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Micro Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "8"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "3"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "0.85"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "Industrial"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Compliant",
        "EuRoHS": "Yes",
        "ChinaRoHS": "Unaffected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/chemical_data/analog devices/604561085md_msop_3x3_8lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2009/8/12/5/18/25/328/txn_/manual/296-8-msop.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "1065404",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0607",
              "notes": "N",
              "qty_available": 591
            }
          ]
        },
        {
          "stock_code": "1590308G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0827",
              "notes": "N",
              "qty_available": 1727
            }
          ]
        },
        {
          "stock_code": "1590310",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0827",
              "notes": "N",
              "qty_available": 1000
            }
          ]
        },
        {
          "stock_code": "2018000",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1038",
              "notes": "N",
              "qty_available": 831
            }
          ]
        },
        {
          "stock_code": "2426629",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1114",
              "notes": "N",
              "qty_available": 955
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARMZ-3.3-R7",
      "part_number": "ADP3333ARMZ-3.3-R7",
      "search_part": "ADP3333ARMZ-3.3-R7|1TS519816.1",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 1000,
      "carrier_type": "REEL7",
      "total_qty_for_part": 4008,
      "EuRoHS": "Yes",
      "ChinaRoHS": "Unaffected",
      "LeadFreeStatus": "Compliant",
      "tech_desc": "N/A",
      "drawing": "BROKEN TR DP ROHS",
      "sell_part": "YES",
      "distributor_price": 0.83,
      "prices": {
        "p1_24": 1.28,
        "p25_99": 1.19,
        "p100_499": 1.14,
        "p500_999": 1.09,
        "over_1000": 1.04
      },
      "build": 0,
      "se_data": {
        "PartNumber": "ADP3333ARMZ-3.3-R7",
        "Description": "LDO Regulator Pos 3.3V 0.6A 8-Pin MSOP T/R",
        "RoHS": "Yes",
        "Lifecycle": "Active",
        "ComID": "19977572",
        "ProductLine": "Linear Regulator",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2009/4/22/5/18/8/adi_/auto/adp3333.pdf",
        "Family": "ADP3333",
        "Generic": "",
        "LTBDate": "",
        "CageCode": "24355",
        "TaxonomyPath": "Power Management > Linear Regulators and Controllers > Linear Regulator",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Linear Regulators and Controllers",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "MSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Micro Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "8"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "3"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "0.85"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "Industrial"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Compliant",
        "EuRoHS": "Yes",
        "ChinaRoHS": "Unaffected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/chemical_data/analog devices/604561085md_msop_3x3_8lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2009/8/12/5/18/25/328/txn_/manual/296-8-msop.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "1108488",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "MIX06",
              "notes": "N",
              "qty_available": 1000
            }
          ]
        },
        {
          "stock_code": "1108608",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "MIX06",
              "notes": "N",
              "qty_available": 800
            }
          ]
        },
        {
          "stock_code": "1915378",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1018",
              "notes": "N",
              "qty_available": 632
            }
          ]
        },
        {
          "stock_code": "1930858",
          "long_description": "M: 1TS519816.1",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1010",
              "notes": "N",
              "qty_available": 404
            }
          ]
        },
        {
          "stock_code": "2017803",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1037",
              "notes": "N",
              "qty_available": 7
            }
          ]
        },
        {
          "stock_code": "2580625",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "MIX 14",
              "notes": "N",
              "qty_available": 1000
            }
          ]
        },
        {
          "stock_code": "2607700",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "REEL7",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1203",
              "notes": "N",
              "qty_available": 165
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAADP3333ARMZ-3.3-RL",
      "part_number": "ADP3333ARMZ-3.3-RL",
      "search_part": "ADP3333ARMZ-3.3-RL",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 3000,
      "carrier_type": "REEL",
      "total_qty_for_part": 1683,
      "EuRoHS": "Yes",
      "ChinaRoHS": "Unaffected",
      "LeadFreeStatus": "Compliant",
      "tech_desc": "N/A",
      "drawing": "BROKEN TR LF ROHS",
      "sell_part": "YES",
      "distributor_price": 0.83,
      "prices": {
        "p1_24": 1.28,
        "p25_99": 1.19,
        "p100_499": 1.14,
        "p500_999": 1.09,
        "over_1000": 1.04
      },
      "build": 0,
      "se_data": {
        "PartNumber": "ADP3333ARMZ-3.3-RL",
        "Description": "LDO Regulator Pos 3.3V 0.6A 8-Pin MSOP T/R",
        "RoHS": "Yes",
        "Lifecycle": "Obsolete",
        "ComID": "19977619",
        "ProductLine": "Linear Regulator",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2009/4/22/5/18/8/adi_/auto/adp3333.pdf",
        "Family": "ADP3333",
        "Generic": "",
        "LTBDate": "05/14/2011",
        "CageCode": "24355",
        "TaxonomyPath": "Power Management > Linear Regulators and Controllers > Linear Regulator",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Linear Regulators and Controllers",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "MSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Micro Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "8"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "3"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "0.85"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "Industrial"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Compliant",
        "EuRoHS": "Yes",
        "ChinaRoHS": "Unaffected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/chemical_data/analog devices/604561085md_msop_3x3_8lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2009/8/12/5/18/25/328/txn_/manual/296-8-msop.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "1456971",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 3000,
          "carrier_type": "REEL",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0816",
              "notes": "N",
              "qty_available": 1683
            }
          ]
        }
      ]
    },
    {
      "_id": "NATNSCLF13333D",
      "part_number": "LF13333D",
      "search_part": "LF13333D|1826-0417",
      "manufacturer": "NSC",
      "supplier": "NAT",
      "mpq": "0",
      "carrier_type": "",
      "total_qty_for_part": 1287,
      "EuRoHS": "NO",
      "LeadFreeStatus": "NO",
      "ChinaRoHS": "",
      "tech_desc": "N/A",
      "drawing": "N/A",
      "sell_part": "YES",
      "distributor_price": 8.15,
      "prices": {
        "p1_24": 12.54,
        "p25_99": 11.64,
        "p100_499": 11.16,
        "p500_999": 10.72,
        "over_1000": 10.19
      },
      "build": 0,
      "se_data": "",
      "stock_codes": [
        {
          "stock_code": "13333",
          "long_description": "M: 1826-0417",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "9736",
              "notes": "N",
              "qty_available": 165
            }
          ]
        },
        {
          "stock_code": "13333-0001",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "9806",
              "notes": "N",
              "qty_available": 1122
            }
          ]
        }
      ]
    },
    {
      "_id": "TEXNSCLP3986TL-3333/NOPB",
      "part_number": "LP3986TL-3333/NOPB",
      "search_part": "LP3986TL-3333/NOPB",
      "manufacturer": "NSC",
      "supplier": "TEX",
      "mpq": "0",
      "carrier_type": "",
      "total_qty_for_part": 2585,
      "EuRoHS": "YES",
      "LeadFreeStatus": "YES",
      "ChinaRoHS": "",
      "tech_desc": "N/A",
      "drawing": "P1 BROKEN TR DP LF ROHS",
      "sell_part": "YES",
      "distributor_price": 0.38,
      "prices": {
        "p1_24": 0.58,
        "p25_99": 0.54,
        "p100_499": 0.52,
        "p500_999": 0.5,
        "over_1000": 0.48
      },
      "build": 0,
      "se_data": "",
      "stock_codes": [
        {
          "stock_code": "1835027",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0912",
              "notes": "N",
              "qty_available": 250
            }
          ]
        },
        {
          "stock_code": "2088854",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1148",
              "notes": "N",
              "qty_available": 2250
            }
          ]
        },
        {
          "stock_code": "2088855",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1148",
              "notes": "N",
              "qty_available": 85
            }
          ]
        }
      ]
    },
    {
      "_id": "TEXNSCLP3996SD-3333/NOPB",
      "part_number": "LP3996SD-3333/NOPB",
      "search_part": "LP3996SD-3333/NOPB",
      "manufacturer": "NSC",
      "supplier": "TEX",
      "mpq": "0",
      "carrier_type": "",
      "total_qty_for_part": 4739,
      "EuRoHS": "YES",
      "LeadFreeStatus": "YES",
      "ChinaRoHS": "",
      "tech_desc": "N/A",
      "drawing": "TR QTY 1000 LF ROHS",
      "sell_part": "YES",
      "distributor_price": 0.33,
      "prices": {
        "p1_24": 0.51,
        "p25_99": 0.47,
        "p100_499": 0.45,
        "p500_999": 0.43,
        "over_1000": 0.41
      },
      "build": 0,
      "se_data": "",
      "stock_codes": [
        {
          "stock_code": "1652265",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0906",
              "notes": "N",
              "qty_available": 739
            }
          ]
        },
        {
          "stock_code": "1721866",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1112",
              "notes": "N",
              "qty_available": 1000
            }
          ]
        },
        {
          "stock_code": "1847064",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1112",
              "notes": "N",
              "qty_available": 1000
            }
          ]
        },
        {
          "stock_code": "2090051",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0906",
              "notes": "N",
              "qty_available": 1000
            }
          ]
        },
        {
          "stock_code": "2405908",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1112",
              "notes": "N",
              "qty_available": 1000
            }
          ]
        }
      ]
    },
    {
      "_id": "TEXTISLP3996SD-3333/NOPB",
      "part_number": "LP3996SD-3333/NOPB",
      "search_part": "LP3996SD-3333/NOPB",
      "manufacturer": "TIS",
      "supplier": "TEX",
      "mpq": 1000,
      "carrier_type": "",
      "total_qty_for_part": 299,
      "EuRoHS": "Yes",
      "ChinaRoHS": "Unaffected",
      "LeadFreeStatus": "Compliant",
      "tech_desc": "N/A",
      "drawing": "BROKEN TR DP LF ROHS",
      "sell_part": "YES",
      "distributor_price": 0.33,
      "prices": {
        "p1_24": 0.51,
        "p25_99": 0.47,
        "p100_499": 0.45,
        "p500_999": 0.43,
        "over_1000": 0.41
      },
      "build": 0,
      "se_data": {
        "PartNumber": "LP3996SD-3333/NOPB",
        "Description": "LDO Regulator Pos 3.3V3.3V 0.15A/0.3A 10-Pin WSON EP T/R",
        "RoHS": "Yes",
        "Lifecycle": "Active",
        "ComID": "27731945",
        "ProductLine": "Linear Regulator",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2014/9/16/3/34/8/683/txn_/manual/825lp3996.pdf",
        "Family": "LP3996",
        "Generic": "",
        "LTBDate": "",
        "CageCode": "01295",
        "TaxonomyPath": "Power Management > Linear Regulators and Controllers > Linear Regulator",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Linear Regulators and Controllers",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Non-Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "SON"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Very Very Thin Small Outline No Lead Package, Exposed Pad"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "No Lead"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "10"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3.15(Max)"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "3.15(Max)"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "0.75(Max)"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "0.8(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.5"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "N/A"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Compliant",
        "EuRoHS": "Yes",
        "ChinaRoHS": "Unaffected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/2014/5/19/10/42/43/445/txn_/manual/detail.xls",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2014/4/16/7/35/20/554/txn_/manual/tps61230dsct.jpg",
        "manufacturerName": "Texas Instruments",
        "manufacturer": "TIS"
      },
      "stock_codes": [
        {
          "stock_code": "2406174",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 1000,
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "9999",
              "notes": "N",
              "qty_available": 299
            }
          ]
        }
      ]
    },
    {
      "_id": "TEXTISREF3333AIDBZR",
      "part_number": "REF3333AIDBZR",
      "search_part": "REF3333AIDBZR",
      "manufacturer": "TIS",
      "supplier": "TEX",
      "mpq": 3000,
      "carrier_type": "",
      "total_qty_for_part": 136500,
      "EuRoHS": "Yes",
      "ChinaRoHS": "Unaffected",
      "LeadFreeStatus": "Compliant",
      "tech_desc": "N/A",
      "drawing": "P1 TR 3000 DP LF ROHS",
      "sell_part": "YES",
      "distributor_price": 0.94,
      "prices": {
        "p1_24": 1.45,
        "p25_99": 1.34,
        "p100_499": 1.29,
        "p500_999": 1.24,
        "over_1000": 1.18
      },
      "build": 0,
      "se_data": {
        "PartNumber": "REF3333AIDBZR",
        "Description": "V-Ref Precision 3.3V 5mA 3-Pin SOT-23 T/R",
        "RoHS": "Yes",
        "Lifecycle": "Active",
        "ComID": "31007418",
        "ProductLine": "Voltage Reference",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2015/5/17/8/17/17/639/txn_/manual/getliterature.tspgenericpartnumberref3325ampfiletypepdf.tspgeneri.pdf",
        "Family": "REF3333",
        "Generic": "",
        "LTBDate": "",
        "CageCode": "01295",
        "TaxonomyPath": "Power Management > Application Specific > Voltage Reference",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Application Specific",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "SOT-23"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Small Outline Transistor"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "3"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3.04(Max)"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "1.4(Max)"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "1.02(Max)"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.12(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.95"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "125"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "N/A"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Compliant",
        "EuRoHS": "Yes",
        "ChinaRoHS": "Unaffected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/2014/5/19/10/42/19/707/txn_/manual/ref3333aidbzr.xls",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2013/11/13/8/47/56/62/txn_/manual/lm4041qcem3x-1.2no.jpg",
        "manufacturerName": "Texas Instruments",
        "manufacturer": "TIS"
      },
      "stock_codes": [
        {
          "stock_code": "1347950",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 3000,
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "9999",
              "notes": "N",
              "qty_available": 1500
            }
          ]
        },
        {
          "stock_code": "2358007G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 3000,
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "1049",
              "notes": "N",
              "qty_available": 27000
            }
          ]
        },
        {
          "stock_code": "2446022G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 3000,
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1231",
              "notes": "N",
              "qty_available": 51000
            }
          ]
        },
        {
          "stock_code": "2484822G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 3000,
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1236",
              "notes": "N",
              "qty_available": 12000
            }
          ]
        },
        {
          "stock_code": "2503930G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 3000,
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1244",
              "notes": "N",
              "qty_available": 39000
            },
            {
              "warehouse": "04",
              "date_code": "1249",
              "notes": "N",
              "qty_available": 3000
            }
          ]
        },
        {
          "stock_code": "784098",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 3000,
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0827",
              "notes": "N",
              "qty_available": 3000
            }
          ]
        }
      ]
    },
    {
      "_id": "TEXTISREF3333AIDBZT",
      "part_number": "REF3333AIDBZT",
      "search_part": "REF3333AIDBZT",
      "manufacturer": "TIS",
      "supplier": "TEX",
      "mpq": 250,
      "carrier_type": "",
      "total_qty_for_part": 803,
      "EuRoHS": "Yes",
      "ChinaRoHS": "Unaffected",
      "LeadFreeStatus": "Compliant",
      "tech_desc": "N/A",
      "drawing": "P1 TR 250 DP LF",
      "sell_part": "YES",
      "distributor_price": 1.11,
      "prices": {
        "p1_24": 1.71,
        "p25_99": 1.59,
        "p100_499": 1.52,
        "p500_999": 1.46,
        "over_1000": 1.39
      },
      "build": 0,
      "se_data": {
        "PartNumber": "REF3333AIDBZT",
        "Description": "V-Ref Precision 3.3V 5mA 3-Pin SOT-23 T/R",
        "RoHS": "Yes",
        "Lifecycle": "Active",
        "ComID": "31007432",
        "ProductLine": "Voltage Reference",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2015/5/17/8/17/17/639/txn_/manual/getliterature.tspgenericpartnumberref3325ampfiletypepdf.tspgeneri.pdf",
        "Family": "REF3333",
        "Generic": "",
        "LTBDate": "",
        "CageCode": "01295",
        "TaxonomyPath": "Power Management > Application Specific > Voltage Reference",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Application Specific",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "SOT-23"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Small Outline Transistor"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "3"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "3.04(Max)"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "1.4(Max)"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "1.02(Max)"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.12(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.95"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "125"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "N/A"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Compliant",
        "EuRoHS": "Yes",
        "ChinaRoHS": "Unaffected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/2014/5/19/14/30/30/133/txn_/manual/24454searchbypcid.tsppcid36645orderablepartref3333aidbztdownloadtruesp.xls",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2013/11/13/8/47/56/62/txn_/manual/lm4041qcem3x-1.2no.jpg",
        "manufacturerName": "Texas Instruments",
        "manufacturer": "TIS"
      },
      "stock_codes": [
        {
          "stock_code": "1354597",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 250,
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "9999",
              "notes": "N",
              "qty_available": 78
            }
          ]
        },
        {
          "stock_code": "1358000",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 250,
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0749",
              "notes": "N",
              "qty_available": 225
            }
          ]
        },
        {
          "stock_code": "2530007",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 250,
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1231+5",
              "notes": "N",
              "qty_available": 250
            }
          ]
        },
        {
          "stock_code": "996603",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 250,
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0749",
              "notes": "N",
              "qty_available": 250
            }
          ]
        }
      ]
    },
    {
      "_id": "TEXTISREF3333AIDCKR",
      "part_number": "REF3333AIDCKR",
      "search_part": "REF3333AIDCKR",
      "manufacturer": "TIS",
      "supplier": "TEX",
      "mpq": 3000,
      "carrier_type": "",
      "total_qty_for_part": 30000,
      "EuRoHS": "Yes",
      "ChinaRoHS": "Unaffected",
      "LeadFreeStatus": "Compliant",
      "tech_desc": "N/A",
      "drawing": "P1 TR 3000 DP LF ROHS",
      "sell_part": "YES",
      "distributor_price": 0.94,
      "prices": {
        "p1_24": 1.45,
        "p25_99": 1.34,
        "p100_499": 1.29,
        "p500_999": 1.24,
        "over_1000": 1.18
      },
      "build": 0,
      "se_data": {
        "PartNumber": "REF3333AIDCKR",
        "Description": "V-Ref Precision 3.3V 5mA 3-Pin SC-70 T/R",
        "RoHS": "Yes",
        "Lifecycle": "Active",
        "ComID": "31007479",
        "ProductLine": "Voltage Reference",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2015/5/17/8/17/17/639/txn_/manual/getliterature.tspgenericpartnumberref3325ampfiletypepdf.tspgeneri.pdf",
        "Family": "REF3333",
        "Generic": "",
        "LTBDate": "",
        "CageCode": "01295",
        "TaxonomyPath": "Power Management > Application Specific > Voltage Reference",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Application Specific",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "SOT-323"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Small Outline Transistor"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "3"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "2.15(Max)"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "1.4(Max)"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "1(Max)"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "125"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "N/A"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Compliant",
        "EuRoHS": "Yes",
        "ChinaRoHS": "Unaffected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/2014/5/19/14/30/34/695/txn_/manual/24456searchbypcid.tsppcid36647orderablepartref3333aidckrdownloadtruesp.xls",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2014/12/28/6/0/28/873/txn_/manual/tpd2e2u06qdckrq1.jpg",
        "manufacturerName": "Texas Instruments",
        "manufacturer": "TIS"
      },
      "stock_codes": [
        {
          "stock_code": "1334462G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 3000,
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0814",
              "notes": "N",
              "qty_available": 30000
            }
          ]
        }
      ]
    },
    {
      "_id": "TEXTISREF3333AIDCKT",
      "part_number": "REF3333AIDCKT",
      "search_part": "REF3333AIDCKT",
      "manufacturer": "TIS",
      "supplier": "TEX",
      "mpq": 250,
      "carrier_type": "",
      "total_qty_for_part": 12750,
      "EuRoHS": "Yes",
      "ChinaRoHS": "Unaffected",
      "LeadFreeStatus": "Compliant",
      "tech_desc": "N/A",
      "drawing": "P1 TR 250 DP LF ROHS",
      "sell_part": "YES",
      "distributor_price": 1.11,
      "prices": {
        "p1_24": 1.71,
        "p25_99": 1.59,
        "p100_499": 1.52,
        "p500_999": 1.46,
        "over_1000": 1.39
      },
      "build": 0,
      "se_data": {
        "PartNumber": "REF3333AIDCKT",
        "Description": "V-Ref Precision 3.3V 5mA 3-Pin SC-70 T/R",
        "RoHS": "Yes",
        "Lifecycle": "Active",
        "ComID": "31007433",
        "ProductLine": "Voltage Reference",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2015/5/17/8/17/17/639/txn_/manual/getliterature.tspgenericpartnumberref3325ampfiletypepdf.tspgeneri.pdf",
        "Family": "REF3333",
        "Generic": "",
        "LTBDate": "",
        "CageCode": "01295",
        "TaxonomyPath": "Power Management > Application Specific > Voltage Reference",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Application Specific",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "SOT-323"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Small Outline Transistor"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "3"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "2.15(Max)"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "1.4(Max)"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "1(Max)"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.1(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "125"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "N/A"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Compliant",
        "EuRoHS": "Yes",
        "ChinaRoHS": "Unaffected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/2014/5/19/14/30/36/804/txn_/manual/24457searchbypcid.tsppcid36649orderablepartref3333aidcktdownloadtruesp.xls",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2014/12/28/6/0/28/873/txn_/manual/tpd2e2u06qdckrq1.jpg",
        "manufacturerName": "Texas Instruments",
        "manufacturer": "TIS"
      },
      "stock_codes": [
        {
          "stock_code": "1751744G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 250,
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1036",
              "notes": "N",
              "qty_available": 12750
            }
          ]
        }
      ]
    },
    {
      "_id": "SITSITSIT8102AC-33-33E-133.33333Y",
      "part_number": "SIT8102AC-33-33E-133.33333Y",
      "search_part": "SIT8102AC-33-33E-133.33333Y",
      "manufacturer": "SIT",
      "supplier": "SIT",
      "mpq": "0",
      "carrier_type": "",
      "total_qty_for_part": 1000,
      "EuRoHS": "NO",
      "LeadFreeStatus": "NO",
      "ChinaRoHS": "",
      "tech_desc": "N/A",
      "drawing": "TR QTY 1000",
      "sell_part": "YES",
      "distributor_price": 0.8,
      "prices": {
        "p1_24": 1.23,
        "p25_99": 1.14,
        "p100_499": 1.1,
        "p500_999": 1.05,
        "over_1000": 1
      },
      "build": 0,
      "se_data": "",
      "stock_codes": [
        {
          "stock_code": "3004956",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1431",
              "notes": "N",
              "qty_available": 1000
            }
          ]
        }
      ]
    },
    {
      "_id": "SITSITSIT8103AC-31-18E-33.33333T",
      "part_number": "SIT8103AC-31-18E-33.33333T",
      "search_part": "SIT8103AC-31-18E-33.33333T",
      "manufacturer": "SIT",
      "supplier": "SIT",
      "mpq": "0",
      "carrier_type": "",
      "total_qty_for_part": 15000,
      "EuRoHS": "NO",
      "LeadFreeStatus": "NO",
      "ChinaRoHS": "",
      "tech_desc": "N/A",
      "drawing": "TR QTY 3000",
      "sell_part": "YES",
      "distributor_price": 0.91,
      "prices": {
        "p1_24": 1.4,
        "p25_99": 1.3,
        "p100_499": 1.25,
        "p500_999": 1.2,
        "over_1000": 1.14
      },
      "build": 0,
      "se_data": "",
      "stock_codes": [
        {
          "stock_code": "3004725G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1432",
              "notes": "N",
              "qty_available": 6000
            },
            {
              "warehouse": "04",
              "date_code": "1435",
              "notes": "N",
              "qty_available": 3000
            },
            {
              "warehouse": "04",
              "date_code": "MIX14",
              "notes": "N",
              "qty_available": 6000
            }
          ]
        }
      ]
    }
  ]
}
