{
  "success": "yes",
  "returned_parts": 17,
  "total_count": 17,
  "mfg_count": {
    "TIS": 6,
    "FSC": 5,
    "ANA": 2,
    "NXP": 4
  },
  "parts": [
    {
      "_id": "NXPNXP74HC5555D112",
      "part_number": "74HC5555D112",
      "search_part": "74HC5555D112|933998590112",
      "manufacturer": "NXP",
      "supplier": "NXP",
      "mpq": "0",
      "carrier_type": "",
      "total_qty_for_part": 850,
      "EuRoHS": "YES",
      "LeadFreeStatus": "YES",
      "ChinaRoHS": "",
      "tech_desc": "N/A",
      "drawing": "LF ROHS",
      "sell_part": "YES",
      "distributor_price": 0.52,
      "prices": {
        "p1_24": 0.8,
        "p25_99": 0.74,
        "p100_499": 0.71,
        "p500_999": 0.68,
        "over_1000": 0.65
      },
      "build": 0,
      "se_data": "",
      "stock_codes": [
        {
          "stock_code": "2568695",
          "long_description": "REF: 933998590112",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "1347",
              "notes": "N",
              "qty_available": 850
            }
          ]
        }
      ]
    },
    {
      "_id": "NXPNXP74HC5555N112",
      "part_number": "74HC5555N112",
      "search_part": "74HC5555N112|933998580112",
      "manufacturer": "NXP",
      "supplier": "NXP",
      "mpq": "0",
      "carrier_type": "",
      "total_qty_for_part": 2095,
      "EuRoHS": "YES",
      "LeadFreeStatus": "NO",
      "ChinaRoHS": "",
      "tech_desc": "N/A",
      "drawing": "ROHS",
      "sell_part": "YES",
      "distributor_price": 1.33,
      "prices": {
        "p1_24": 2.05,
        "p25_99": 1.9,
        "p100_499": 1.82,
        "p500_999": 1.75,
        "over_1000": 1.66
      },
      "build": 0,
      "se_data": "",
      "stock_codes": [
        {
          "stock_code": "2037745",
          "long_description": "REF: 933998580112",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1230",
              "notes": "N",
              "qty_available": 1000
            }
          ]
        },
        {
          "stock_code": "2267521",
          "long_description": "933998580112",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1125",
              "notes": "N",
              "qty_available": 375
            }
          ]
        },
        {
          "stock_code": "2316632",
          "long_description": "933998580112",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "MIX 09+",
              "notes": "N",
              "qty_available": 500
            }
          ]
        },
        {
          "stock_code": "2516136",
          "long_description": "REF: 933998580112",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "1347",
              "notes": "N",
              "qty_available": 220
            }
          ]
        }
      ]
    },
    {
      "_id": "NXPNXP74HCT5555D112",
      "part_number": "74HCT5555D112",
      "search_part": "74HCT5555D112|933998610112",
      "manufacturer": "NXP",
      "supplier": "NXP",
      "mpq": "0",
      "carrier_type": "",
      "total_qty_for_part": 12556,
      "EuRoHS": "YES",
      "LeadFreeStatus": "YES",
      "ChinaRoHS": "",
      "tech_desc": "N/A",
      "drawing": "LF ROHS",
      "sell_part": "YES",
      "distributor_price": 0.69,
      "prices": {
        "p1_24": 1.06,
        "p25_99": 0.99,
        "p100_499": 0.95,
        "p500_999": 0.91,
        "over_1000": 0.86
      },
      "build": 0,
      "se_data": "",
      "stock_codes": [
        {
          "stock_code": "2171540",
          "long_description": "REF: 933998610112",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1050",
              "notes": "N",
              "qty_available": 1000
            }
          ]
        },
        {
          "stock_code": "2752794G",
          "long_description": "REF: 933998610112",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1016",
              "notes": "N",
              "qty_available": 6556
            },
            {
              "warehouse": "04",
              "date_code": "1109",
              "notes": "N",
              "qty_available": 1000
            },
            {
              "warehouse": "04",
              "date_code": "1110",
              "notes": "N",
              "qty_available": 1000
            },
            {
              "warehouse": "04",
              "date_code": "MIX10",
              "notes": "N",
              "qty_available": 2000
            },
            {
              "warehouse": "04",
              "date_code": "MIX11",
              "notes": "N",
              "qty_available": 1000
            }
          ]
        }
      ]
    },
    {
      "_id": "NXPNXP74HCT5555N112",
      "part_number": "74HCT5555N112",
      "search_part": "74HCT5555N112|933998600112",
      "manufacturer": "NXP",
      "supplier": "NXP",
      "mpq": "0",
      "carrier_type": "",
      "total_qty_for_part": 1737,
      "EuRoHS": "YES",
      "LeadFreeStatus": "YES",
      "ChinaRoHS": "",
      "tech_desc": "N/A",
      "drawing": "LF ROHS",
      "sell_part": "YES",
      "distributor_price": 1.33,
      "prices": {
        "p1_24": 2.05,
        "p25_99": 1.9,
        "p100_499": 1.82,
        "p500_999": 1.75,
        "over_1000": 1.66
      },
      "build": 0,
      "se_data": "",
      "stock_codes": [
        {
          "stock_code": "2166786",
          "long_description": "REF: 933998600112",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1045",
              "notes": "N",
              "qty_available": 1000
            }
          ]
        },
        {
          "stock_code": "2699589",
          "long_description": "REF: 933998600112",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "1307",
              "notes": "N",
              "qty_available": 737
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAAD5555CRU",
      "part_number": "AD5555CRU",
      "search_part": "AD5555CRU",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 96,
      "carrier_type": "TUBE",
      "total_qty_for_part": 7209,
      "EuRoHS": "No",
      "ChinaRoHS": "Affected",
      "LeadFreeStatus": "Not Compliant",
      "tech_desc": "N/A",
      "drawing": "N/A",
      "sell_part": "YES",
      "distributor_price": 10.02,
      "prices": {
        "p1_24": 15.42,
        "p25_99": 14.31,
        "p100_499": 13.73,
        "p500_999": 13.18,
        "over_1000": 12.53
      },
      "build": 0,
      "se_data": {
        "PartNumber": "AD5555CRU",
        "Description": "DAC 2-CH R-2R/Current Steering 14-bit 16-Pin TSSOP Tube",
        "RoHS": "No",
        "Lifecycle": "Active",
        "ComID": "18176333",
        "ProductLine": "DAC",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2014/4/25/22/20/22/203/adi_/manual/2116ad5545_5555.pdf",
        "Family": "AD5555",
        "Generic": "",
        "LTBDate": "",
        "CageCode": "24355",
        "TaxonomyPath": "Data Acquisition > Data Converters > DAC",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Data Converters",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "TSSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Thin Shrink Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "16"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "5"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "4.4"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "1.05(Max)"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.2(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "N/A"
        },
        "Packaging": "Tube",
        "LeadFreeStatus": "Not Compliant",
        "EuRoHS": "No",
        "ChinaRoHS": "Affected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/2008/05/07/isys/adi/24994151tssop_4.4_16lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2011/8/7/0/59/58/867/adi_/manual/tssop-16.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "1128220",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 96,
          "carrier_type": "TUBE",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0606",
              "notes": "N",
              "qty_available": 677
            }
          ]
        },
        {
          "stock_code": "1343792",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 96,
          "carrier_type": "TUBE",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0741",
              "notes": "N",
              "qty_available": 1710
            }
          ]
        },
        {
          "stock_code": "275242G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 96,
          "carrier_type": "TUBE",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "0312",
              "notes": "N",
              "qty_available": 1066
            },
            {
              "warehouse": "02",
              "date_code": "0314",
              "notes": "N",
              "qty_available": 1418
            }
          ]
        },
        {
          "stock_code": "2969450",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 96,
          "carrier_type": "TUBE",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1213",
              "notes": "N",
              "qty_available": 2293
            }
          ]
        },
        {
          "stock_code": "309500G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 96,
          "carrier_type": "TUBE",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "0314",
              "notes": "N",
              "qty_available": 38
            }
          ]
        },
        {
          "stock_code": "355043",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 96,
          "carrier_type": "TUBE",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "0310",
              "notes": "N",
              "qty_available": 7
            }
          ]
        }
      ]
    },
    {
      "_id": "ANAANAAD5555CRUZ",
      "part_number": "AD5555CRUZ",
      "search_part": "AD5555CRUZ",
      "manufacturer": "ANA",
      "supplier": "ANA",
      "mpq": 96,
      "carrier_type": "TUBE",
      "total_qty_for_part": 1074,
      "EuRoHS": "Yes",
      "ChinaRoHS": "Unaffected",
      "LeadFreeStatus": "Compliant",
      "tech_desc": "N/A",
      "drawing": "ROHS",
      "sell_part": "YES",
      "distributor_price": 9.11,
      "prices": {
        "p1_24": 14.02,
        "p25_99": 13.01,
        "p100_499": 12.48,
        "p500_999": 11.99,
        "over_1000": 11.39
      },
      "build": 0,
      "se_data": {
        "PartNumber": "AD5555CRUZ",
        "Description": "DAC 2-CH R-2R/Current Steering 14-bit 16-Pin TSSOP Tube",
        "RoHS": "Yes",
        "Lifecycle": "Active",
        "ComID": "18176336",
        "ProductLine": "DAC",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2014/4/25/22/20/22/203/adi_/manual/2116ad5545_5555.pdf",
        "Family": "AD5555",
        "Generic": "",
        "LTBDate": "",
        "CageCode": "24355",
        "TaxonomyPath": "Data Acquisition > Data Converters > DAC",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8542390000",
        "ScheduleB": "8542390000",
        "SubCategory": "Data Converters",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "TSSOP"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Thin Shrink Small Outline Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "16"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "5"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "4.4"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "1.05(Max)"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "1.2(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "0.65"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-40"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "85"
        },
        "SupplierTemperatureGrade": {
          "Name": "Supplier Temperature Grade",
          "Value": "N/A"
        },
        "Packaging": "Tube",
        "LeadFreeStatus": "Compliant",
        "EuRoHS": "Yes",
        "ChinaRoHS": "Unaffected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/2008/05/07/isys/adi/24994151tssop_4.4_16lds.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2011/8/7/0/59/58/867/adi_/manual/tssop-16.jpg",
        "manufacturerName": "Analog Devices",
        "manufacturer": "ANA"
      },
      "stock_codes": [
        {
          "stock_code": "1442113G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 96,
          "carrier_type": "TUBE",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1014",
              "notes": "N",
              "qty_available": 189
            },
            {
              "warehouse": "04",
              "date_code": "1022",
              "notes": "N",
              "qty_available": 214
            },
            {
              "warehouse": "04",
              "date_code": "1051",
              "notes": "N",
              "qty_available": 140
            }
          ]
        },
        {
          "stock_code": "1456404G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 96,
          "carrier_type": "TUBE",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1014",
              "notes": "N",
              "qty_available": 180
            }
          ]
        },
        {
          "stock_code": "1621414",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 96,
          "carrier_type": "TUBE",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1051",
              "notes": "N",
              "qty_available": 38
            }
          ]
        },
        {
          "stock_code": "2083806G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 96,
          "carrier_type": "TUBE",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1244",
              "notes": "N",
              "qty_available": 273
            }
          ]
        },
        {
          "stock_code": "2695175G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 96,
          "carrier_type": "TUBE",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1218",
              "notes": "N",
              "qty_available": 2
            },
            {
              "warehouse": "04",
              "date_code": "1417",
              "notes": "N",
              "qty_available": 38
            }
          ]
        }
      ]
    },
    {
      "_id": "FAIFSCFJB5555TM",
      "part_number": "FJB5555TM",
      "search_part": "FJB5555TM",
      "manufacturer": "FSC",
      "supplier": "FAI",
      "mpq": "0",
      "carrier_type": "",
      "total_qty_for_part": 929,
      "EuRoHS": "Yes",
      "ChinaRoHS": "Affected",
      "LeadFreeStatus": "Not Compliant",
      "tech_desc": "N/A",
      "drawing": "BROKEN TR DP LF ROHS",
      "sell_part": "YES",
      "distributor_price": 0.44,
      "prices": {
        "p1_24": 0.68,
        "p25_99": 0.63,
        "p100_499": 0.6,
        "p500_999": 0.58,
        "over_1000": 0.55
      },
      "build": 0,
      "se_data": {
        "PartNumber": "FJB5555TM",
        "Description": "Trans GP BJT NPN 400V 5A 3-Pin(2+Tab) D2PAK T/R",
        "RoHS": "Yes",
        "Lifecycle": "Active",
        "ComID": "48017619",
        "ProductLine": "GP BJT",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2013/6/22/14/42/54/377/fsc_/auto/846fjb5555.pdf",
        "Family": "FJB5555",
        "Generic": "",
        "LTBDate": "",
        "CageCode": "07933",
        "TaxonomyPath": "Diodes, Transistors and Thyristors > Bipolar Transistors > GP BJT",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8541290095",
        "ScheduleB": "8541290080",
        "SubCategory": "Bipolar Transistors",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "D2PAK"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Double Deca Watt Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "3"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "10.67(Max)"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "9.65(Max)"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "4.83(Max)"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "4.83(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "2.54"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-55"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "150"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Not Compliant",
        "EuRoHS": "Yes",
        "ChinaRoHS": "Affected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/2015/4/4/9/40/5/482/fsc_/manual/35533622422394224fjb5555tm.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2011/3/24/2/49/9/590/fsc_/manual/d2pak-3.jpg",
        "manufacturerName": "Fairchild Semiconductor",
        "manufacturer": "FSC"
      },
      "stock_codes": [
        {
          "stock_code": "2436702",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1123",
              "notes": "N",
              "qty_available": 446
            }
          ]
        },
        {
          "stock_code": "2676582",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1333",
              "notes": "N",
              "qty_available": 483
            }
          ]
        }
      ]
    },
    {
      "_id": "FAIFSCFJD5555TM",
      "part_number": "FJD5555TM",
      "search_part": "FJD5555TM",
      "manufacturer": "FSC",
      "supplier": "FAI",
      "mpq": 2500,
      "carrier_type": "TAPE REEL",
      "total_qty_for_part": 1592,
      "EuRoHS": "Yes",
      "ChinaRoHS": "Affected",
      "LeadFreeStatus": "Not Compliant",
      "tech_desc": "N/A",
      "drawing": "LF ROHS",
      "sell_part": "YES",
      "distributor_price": 0.25,
      "prices": {
        "p1_24": 0.38,
        "p25_99": 0.36,
        "p100_499": 0.34,
        "p500_999": 0.33,
        "over_1000": 0.31
      },
      "build": 0,
      "se_data": {
        "PartNumber": "FJD5555TM",
        "Description": "Trans GP BJT NPN 400V 5A 3-Pin(2+Tab) DPAK T/R",
        "RoHS": "Yes",
        "Lifecycle": "Active",
        "ComID": "31268389",
        "ProductLine": "GP BJT",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2013/6/22/12/7/26/516/fsc_/auto/57fjd5555.pdf",
        "Family": "FJD5555",
        "Generic": "",
        "LTBDate": "",
        "CageCode": "07933",
        "TaxonomyPath": "Diodes, Transistors and Thyristors > Bipolar Transistors > GP BJT",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8541290095",
        "ScheduleB": "8541290080",
        "SubCategory": "Bipolar Transistors",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Lead-Frame SMT"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "DPAK"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Deca Watt Package"
        },
        "LeadShape": {
          "Name": "Lead Shape",
          "Value": "Gull-wing"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "3"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "6.6"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "6.1"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "2.3"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "2.3"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "2.3"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-55"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "150"
        },
        "Packaging": "Tape and Reel",
        "LeadFreeStatus": "Not Compliant",
        "EuRoHS": "Yes",
        "ChinaRoHS": "Affected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/2015/7/20/19/11/49/954/fsc_/manual/44812349233438248fjd5555tm.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2011/11/1/2/44/37/727/fsc_/manual/dpak-3.jpg",
        "manufacturerName": "Fairchild Semiconductor",
        "manufacturer": "FSC"
      },
      "stock_codes": [
        {
          "stock_code": "1680990",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 2500,
          "carrier_type": "TAPE REEL",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0941",
              "notes": "N",
              "qty_available": 941
            }
          ]
        },
        {
          "stock_code": "2115886",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 2500,
          "carrier_type": "TAPE REEL",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1145",
              "notes": "N",
              "qty_available": 651
            }
          ]
        }
      ]
    },
    {
      "_id": "FAIFSCFJP5555ATU",
      "part_number": "FJP5555ATU",
      "search_part": "FJP5555ATU",
      "manufacturer": "FSC",
      "supplier": "FAI",
      "mpq": "0",
      "carrier_type": "",
      "total_qty_for_part": 1676,
      "EuRoHS": null,
      "ChinaRoHS": "",
      "LeadFreeStatus": null,
      "tech_desc": "N/A",
      "drawing": "LF ROHS",
      "sell_part": "NO",
      "distributor_price": 0,
      "prices": {
        "p1_24": 0,
        "p25_99": 0,
        "p100_499": 0,
        "p500_999": 0,
        "over_1000": 0
      },
      "build": 0,
      "se_data": {
        "PartNumber": "FJP5555ATU",
        "Description": "TRANSISTORS BIPOLAR - BJT",
        "RoHS": "Yes",
        "Lifecycle": "",
        "ComID": "62432142",
        "ProductLine": "GP BJT",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2008/06/30/semi_ap/cs/fsc/ds/nods.pdf",
        "Family": "FJP5555ATU",
        "Generic": "",
        "LTBDate": "",
        "CageCode": "07933",
        "TaxonomyPath": "Diodes, Transistors and Thyristors > Bipolar Transistors > GP BJT",
        "Eccn": "",
        "RadHard": "",
        "Htsusa": "",
        "ScheduleB": "",
        "SubCategory": "Bipolar Transistors",
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "N/A"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "N/A"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "N/A"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "N/A"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "N/A"
        },
        "manufacturerName": "Fairchild Semiconductor",
        "manufacturer": "FSC"
      },
      "stock_codes": [
        {
          "stock_code": "1682415",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0944",
              "notes": "N",
              "qty_available": 725
            }
          ]
        },
        {
          "stock_code": "2114872",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1145",
              "notes": "N",
              "qty_available": 951
            }
          ]
        }
      ]
    },
    {
      "_id": "FAIFSCFJP5555STU",
      "part_number": "FJP5555STU",
      "search_part": "FJP5555STU",
      "manufacturer": "FSC",
      "supplier": "FAI",
      "mpq": "0",
      "carrier_type": "",
      "total_qty_for_part": 8888,
      "EuRoHS": "YES",
      "LeadFreeStatus": "YES",
      "ChinaRoHS": "",
      "tech_desc": "N/A",
      "drawing": "LF ROHS",
      "sell_part": "NO",
      "distributor_price": 0,
      "prices": {
        "p1_24": 0,
        "p25_99": 0,
        "p100_499": 0,
        "p500_999": 0,
        "over_1000": 0
      },
      "build": 0,
      "se_data": "",
      "stock_codes": [
        {
          "stock_code": "1867680G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1121",
              "notes": "N",
              "qty_available": 8000
            }
          ]
        },
        {
          "stock_code": "2114620",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1145",
              "notes": "N",
              "qty_available": 888
            }
          ]
        }
      ]
    },
    {
      "_id": "FAIFSCFJP5555TU",
      "part_number": "FJP5555TU",
      "search_part": "FJP5555TU",
      "manufacturer": "FSC",
      "supplier": "FAI",
      "mpq": 50,
      "carrier_type": "RAIL",
      "total_qty_for_part": 2012,
      "EuRoHS": "Yes",
      "ChinaRoHS": "Affected",
      "LeadFreeStatus": "Not Compliant",
      "tech_desc": "N/A",
      "drawing": "ROHS",
      "sell_part": "YES",
      "distributor_price": 0.26,
      "prices": {
        "p1_24": 0.4,
        "p25_99": 0.37,
        "p100_499": 0.36,
        "p500_999": 0.34,
        "over_1000": 0.33
      },
      "build": 0,
      "se_data": {
        "PartNumber": "FJP5555TU",
        "Description": "Trans GP BJT NPN 400V 5A 3-Pin(3+Tab) TO-220 Rail",
        "RoHS": "Yes",
        "Lifecycle": "Active",
        "ComID": "18999208",
        "ProductLine": "GP BJT",
        "Datasheet": "http://download.siliconexpert.com/pdfs/2013/6/20/7/58/52/593/fsc_/manual/123fjp5555.pdf",
        "Family": "FJP5555",
        "Generic": "",
        "LTBDate": "",
        "CageCode": "07933",
        "TaxonomyPath": "Diodes, Transistors and Thyristors > Bipolar Transistors > GP BJT",
        "Eccn": "EAR99",
        "RadHard": "No",
        "Htsusa": "8541290095",
        "ScheduleB": "8541290080",
        "SubCategory": "Bipolar Transistors",
        "BasicPackageType": {
          "Name": "Basic Package Type",
          "Value": "Through Hole"
        },
        "StandardPackageName": {
          "Name": "Standard Package Name",
          "Value": "TO-220"
        },
        "PackageDescription": {
          "Name": "Package Description",
          "Value": "Transistor Outline Package"
        },
        "PinCount": {
          "Name": "Pin Count",
          "Value": "3"
        },
        "PackageLength": {
          "Name": "Package Length (mm)",
          "Value": "10.67(Max)"
        },
        "PackageWidth": {
          "Name": "Package Width (mm)",
          "Value": "4.83(Max)"
        },
        "PackageHeight": {
          "Name": "Package Height (mm)",
          "Value": "9.4(Max)"
        },
        "SeatedPlaneHeight": {
          "Name": "Seated Plane Height (mm)",
          "Value": "22.86(Max)"
        },
        "PinPitch": {
          "Name": "Pin Pitch (mm)",
          "Value": "2.54"
        },
        "PackageMaterial": {
          "Name": "Package Material",
          "Value": "Plastic"
        },
        "MinOperatingTemp": {
          "Name": "Minimum Operating Temperature (°C)",
          "Value": "-55"
        },
        "MaxOperatingTemp": {
          "Name": "Maximum Operating Temperature (°C)",
          "Value": "150"
        },
        "Packaging": "Rail",
        "LeadFreeStatus": "Not Compliant",
        "EuRoHS": "Yes",
        "ChinaRoHS": "Affected",
        "MaterialDeclaration": "http://download.siliconexpert.com/pdfs/2015/7/20/21/52/21/612/fsc_/manual/44821979881845840fjp5555tu.pdf",
        "ImageUrl": "http://download.siliconexpert.com/pdfs/2014/4/23/8/23/56/107/fsc_/manual/to-220-3_1.jpg",
        "manufacturerName": "Fairchild Semiconductor",
        "manufacturer": "FSC"
      },
      "stock_codes": [
        {
          "stock_code": "1265110G",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 50,
          "carrier_type": "RAIL",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "0821",
              "notes": "N",
              "qty_available": 1043
            }
          ]
        },
        {
          "stock_code": "2749638",
          "long_description": "N/A",
          "tech_note": "N",
          "mpq": 50,
          "carrier_type": "RAIL",
          "warehouses": [
            {
              "warehouse": "04",
              "date_code": "1305",
              "notes": "N",
              "qty_available": 969
            }
          ]
        }
      ]
    },
    {
      "_id": "TEXTISSNJ55551FD",
      "part_number": "SNJ55551FD",
      "search_part": "SNJ55551FD|5962-8605401XA",
      "manufacturer": "TIS",
      "supplier": "TEX",
      "mpq": "0",
      "carrier_type": "",
      "total_qty_for_part": 11,
      "EuRoHS": "NO",
      "LeadFreeStatus": "NO",
      "ChinaRoHS": "",
      "tech_desc": "N/A",
      "drawing": "N/A",
      "sell_part": "YES",
      "distributor_price": 24.92,
      "prices": {
        "p1_24": 38.34,
        "p25_99": 35.6,
        "p100_499": 34.14,
        "p500_999": 32.79,
        "over_1000": 31.15
      },
      "build": 0,
      "se_data": "",
      "stock_codes": [
        {
          "stock_code": "55551-3167",
          "long_description": "DM: 5962-8605401XA",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "9448A",
              "notes": "N",
              "qty_available": 11
            }
          ]
        }
      ]
    },
    {
      "_id": "TEXTISSNJ55551FJ",
      "part_number": "SNJ55551FJ",
      "search_part": "SNJ55551FJ|5962-8605401YA",
      "manufacturer": "TIS",
      "supplier": "TEX",
      "mpq": "0",
      "carrier_type": "",
      "total_qty_for_part": 211,
      "EuRoHS": "NO",
      "LeadFreeStatus": "NO",
      "ChinaRoHS": "",
      "tech_desc": "N/A",
      "drawing": "N/A",
      "sell_part": "YES",
      "distributor_price": 50.48,
      "prices": {
        "p1_24": 77.66,
        "p25_99": 72.11,
        "p100_499": 69.15,
        "p500_999": 66.42,
        "over_1000": 63.1
      },
      "build": 0,
      "se_data": "",
      "stock_codes": [
        {
          "stock_code": "55551-3168",
          "long_description": "DM:5962-8605401YA",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "9221C",
              "notes": "N",
              "qty_available": 211
            }
          ]
        }
      ]
    },
    {
      "_id": "TEXTISSNJ55552FJ",
      "part_number": "SNJ55552FJ",
      "search_part": "SNJ55552FJ|5962-8605402YA",
      "manufacturer": "TIS",
      "supplier": "TEX",
      "mpq": "0",
      "carrier_type": "",
      "total_qty_for_part": 185,
      "EuRoHS": "NO",
      "LeadFreeStatus": "NO",
      "ChinaRoHS": "",
      "tech_desc": "N/A",
      "drawing": "N/A",
      "sell_part": "YES",
      "distributor_price": 50.48,
      "prices": {
        "p1_24": 77.66,
        "p25_99": 72.11,
        "p100_499": 69.15,
        "p500_999": 66.42,
        "over_1000": 63.1
      },
      "build": 0,
      "se_data": "",
      "stock_codes": [
        {
          "stock_code": "55552-3169",
          "long_description": "DM:5962-8605402YA",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "9250A",
              "notes": "N",
              "qty_available": 50
            }
          ]
        },
        {
          "stock_code": "55552-3170",
          "long_description": "DM:5962-8605402YA",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "9245A",
              "notes": "N",
              "qty_available": 135
            }
          ]
        }
      ]
    },
    {
      "_id": "TEXTISSNJ55553FD",
      "part_number": "SNJ55553FD",
      "search_part": "SNJ55553FD|5962-8605501XA",
      "manufacturer": "TIS",
      "supplier": "TEX",
      "mpq": "0",
      "carrier_type": "",
      "total_qty_for_part": 2,
      "EuRoHS": "NO",
      "LeadFreeStatus": "NO",
      "ChinaRoHS": "",
      "tech_desc": "N/A",
      "drawing": "N/A",
      "sell_part": "YES",
      "distributor_price": 27.64,
      "prices": {
        "p1_24": 42.52,
        "p25_99": 39.49,
        "p100_499": 37.86,
        "p500_999": 36.37,
        "over_1000": 34.55
      },
      "build": 0,
      "se_data": "",
      "stock_codes": [
        {
          "stock_code": "55553",
          "long_description": "DM:5962-8605501XA",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "9442A",
              "notes": "N",
              "qty_available": 2
            }
          ]
        }
      ]
    },
    {
      "_id": "TEXTISSNJ55554FD",
      "part_number": "SNJ55554FD",
      "search_part": "SNJ55554FD|5962-8605502XA",
      "manufacturer": "TIS",
      "supplier": "TEX",
      "mpq": "0",
      "carrier_type": "",
      "total_qty_for_part": 9,
      "EuRoHS": "NO",
      "LeadFreeStatus": "NO",
      "ChinaRoHS": "",
      "tech_desc": "N/A",
      "drawing": "N/A",
      "sell_part": "YES",
      "distributor_price": 27.64,
      "prices": {
        "p1_24": 42.52,
        "p25_99": 39.49,
        "p100_499": 37.86,
        "p500_999": 36.37,
        "over_1000": 34.55
      },
      "build": 0,
      "se_data": "",
      "stock_codes": [
        {
          "stock_code": "55554",
          "long_description": "DM:5962-8605502XA",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "9334A",
              "notes": "N",
              "qty_available": 9
            }
          ]
        }
      ]
    },
    {
      "_id": "TEXTISSNJ55554FJ",
      "part_number": "SNJ55554FJ",
      "search_part": "SNJ55554FJ|5962-8605502YA",
      "manufacturer": "TIS",
      "supplier": "TEX",
      "mpq": "0",
      "carrier_type": "",
      "total_qty_for_part": 409,
      "EuRoHS": "NO",
      "LeadFreeStatus": "NO",
      "ChinaRoHS": "",
      "tech_desc": "N/A",
      "drawing": "N/A",
      "sell_part": "YES",
      "distributor_price": 55.97,
      "prices": {
        "p1_24": 86.11,
        "p25_99": 79.96,
        "p100_499": 76.67,
        "p500_999": 73.64,
        "over_1000": 69.96
      },
      "build": 0,
      "se_data": "",
      "stock_codes": [
        {
          "stock_code": "55554-3171",
          "long_description": "DM:5962-8605502YA",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "9246B",
              "notes": "N",
              "qty_available": 234
            }
          ]
        },
        {
          "stock_code": "55554-3172",
          "long_description": "DM:5962-8605502YA",
          "tech_note": "N",
          "mpq": "0",
          "carrier_type": "",
          "warehouses": [
            {
              "warehouse": "02",
              "date_code": "9250A",
              "notes": "N",
              "qty_available": 175
            }
          ]
        }
      ]
    }
  ]
}