{
  "success": "yes",
  "total_count": 247,
  "mfgs": [
    {
      "mfgId": "THM",
      "mfgName": "3M"
    },
    {
      "mfgId": "AEP",
      "mfgName": "A.E. Petsche Co."
    },
    {
      "mfgId": "AVD",
      "mfgName": "Aavid Thermalloy"
    },
    {
      "mfgId": "ABB",
      "mfgName": "ABB"
    },
    {
      "mfgId": "ACT",
      "mfgName": "Actel"
    },
    {
      "mfgId": "ATI",
      "mfgName": "Advantech Embedded Computing"
    },
    {
      "mfgId": "ATR",
      "mfgName": "Aerotronics"
    },
    {
      "mfgId": "AGI",
      "mfgName": "Agilent Technologies"
    },
    {
      "mfgId": "ALL",
      "mfgName": "Allegro"
    },
    {
      "mfgId": "AMD",
      "mfgName": "Advanced Micro Devices"
    },
    {
      "mfgId": "AER",
      "mfgName": "Aeroflex"
    },
    {
      "mfgId": "AMI",
      "mfgName": "AMI Semiconductor"
    },
    {
      "mfgId": "AMP",
      "mfgName": "Ampro"
    },
    {
      "mfgId": "AGE",
      "mfgName": "Agere"
    },
    {
      "mfgId": "ANA",
      "mfgName": "Analog"
    },
    {
      "mfgId": "ALC",
      "mfgName": "Alcoswitch"
    },
    {
      "mfgId": "APX",
      "mfgName": "Apex Microtechnology Corporation"
    },
    {
      "mfgId": "ALT",
      "mfgName": "Altera"
    },
    {
      "mfgId": "AMC",
      "mfgName": "Applied Micro Circuits Corporation"
    },
    {
      "mfgId": "APH",
      "mfgName": "Amphenol"
    },
    {
      "mfgId": "AUG",
      "mfgName": "Augat"
    },
    {
      "mfgId": "AND",
      "mfgName": "ANADIGICS"
    },
    {
      "mfgId": "AVG",
      "mfgName": "Avago"
    },
    {
      "mfgId": "PMI",
      "mfgName": "Analog PMI"
    },
    {
      "mfgId": "AVX",
      "mfgName": "AVX CORPORATION"
    },
    {
      "mfgId": "API",
      "mfgName": "API Delevan"
    },
    {
      "mfgId": "BEN",
      "mfgName": "Benchmarq"
    },
    {
      "mfgId": "ATM",
      "mfgName": "ATMEL"
    },
    {
      "mfgId": "BOU",
      "mfgName": "Bourns"
    },
    {
      "mfgId": "AUS",
      "mfgName": "Austin Semiconductor"
    },
    {
      "mfgId": "BUL",
      "mfgName": "Bulgin"
    },
    {
      "mfgId": "AVA",
      "mfgName": "AVAYA"
    },
    {
      "mfgId": "CMC",
      "mfgName": "C-Mac"
    },
    {
      "mfgId": "BEL",
      "mfgName": "Bell Technologies"
    },
    {
      "mfgId": "CSI",
      "mfgName": "Cataylyst Semiconductor"
    },
    {
      "mfgId": "CHE",
      "mfgName": "Cherry Semiconductor"
    },
    {
      "mfgId": "BIT",
      "mfgName": "Bittware"
    },
    {
      "mfgId": "CSC",
      "mfgName": "Chiplus Semiconductor Corporation"
    },
    {
      "mfgId": "BSI",
      "mfgName": "Brilliance Semiconductor Inc."
    },
    {
      "mfgId": "CFT",
      "mfgName": "Coilcraft"
    },
    {
      "mfgId": "BUR",
      "mfgName": "Burr Brown"
    },
    {
      "mfgId": "CII",
      "mfgName": "Communication Instruments, Inc."
    },
    {
      "mfgId": "CMD",
      "mfgName": "California Micro Devices"
    },
    {
      "mfgId": "CON",
      "mfgName": "Conexant"
    },
    {
      "mfgId": "CCP",
      "mfgName": "Central Semiconductor Corp"
    },
    {
      "mfgId": "CVC",
      "mfgName": "Cvilux Corporation"
    },
    {
      "mfgId": "CHI",
      "mfgName": "Chipcon"
    },
    {
      "mfgId": "DCK",
      "mfgName": "Daishinku Corporation KDS"
    },
    {
      "mfgId": "CIR",
      "mfgName": "Cirrus Logic"
    },
    {
      "mfgId": "DIA",
      "mfgName": "Dialight Corporation"
    },
    {
      "mfgId": "COM",
      "mfgName": "CommLink"
    },
    {
      "mfgId": "DCS",
      "mfgName": "DISTRIBUTOR CONTROL SYSTEMS INC"
    },
    {
      "mfgId": "CEC",
      "mfgName": "Concord Electronics Corporation"
    },
    {
      "mfgId": "EST",
      "mfgName": "Eastek International"
    },
    {
      "mfgId": "CMN",
      "mfgName": "Cummins"
    },
    {
      "mfgId": "EGD",
      "mfgName": "Egide"
    },
    {
      "mfgId": "CYP",
      "mfgName": "Cypress"
    },
    {
      "mfgId": "EAI",
      "mfgName": "Elna America Inc"
    },
    {
      "mfgId": "DSC",
      "mfgName": "Dallas Semiconductor"
    },
    {
      "mfgId": "EMB",
      "mfgName": "EmberInsight"
    },
    {
      "mfgId": "DIC",
      "mfgName": "Diodes Incorporated"
    },
    {
      "mfgId": "EPS",
      "mfgName": "Epson"
    },
    {
      "mfgId": "DPC",
      "mfgName": "DPAC Technologies"
    },
    {
      "mfgId": "EXA",
      "mfgName": "Exar"
    },
    {
      "mfgId": "EFW",
      "mfgName": "EFW Inc"
    },
    {
      "mfgId": "FOX",
      "mfgName": "Fox Electronics"
    },
    {
      "mfgId": "ELA",
      "mfgName": "Elantec"
    },
    {
      "mfgId": "FUJ",
      "mfgName": "Fuji"
    },
    {
      "mfgId": "GAL",
      "mfgName": "Galvantech"
    },
    {
      "mfgId": "EBA",
      "mfgName": "Embedded Artists"
    },
    {
      "mfgId": "GEM",
      "mfgName": "GE Multilin"
    },
    {
      "mfgId": "EPC",
      "mfgName": "Epcos"
    },
    {
      "mfgId": "GNM",
      "mfgName": "Gennum"
    },
    {
      "mfgId": "ERI",
      "mfgName": "Ericsson"
    },
    {
      "mfgId": "GOO",
      "mfgName": "GOODRICH"
    },
    {
      "mfgId": "FSC",
      "mfgName": "Fairchild"
    },
    {
      "mfgId": "HAE",
      "mfgName": "Haemonetics"
    },
    {
      "mfgId": "FRE",
      "mfgName": "Freescale"
    },
    {
      "mfgId": "HSC",
      "mfgName": "Hardware Specialty Co., INC."
    },
    {
      "mfgId": "GAC",
      "mfgName": "Gaia Converter"
    },
    {
      "mfgId": "HIT",
      "mfgName": "Hitachi"
    },
    {
      "mfgId": "GNE",
      "mfgName": "GE Energy"
    },
    {
      "mfgId": "HON",
      "mfgName": "Honeywell"
    },
    {
      "mfgId": "GEN",
      "mfgName": "General Semiconductor"
    },
    {
      "mfgId": "IBM",
      "mfgName": "IBM"
    },
    {
      "mfgId": "GEW",
      "mfgName": "Gewiss"
    },
    {
      "mfgId": "IDT",
      "mfgName": "IDT"
    },
    {
      "mfgId": "GHS",
      "mfgName": "Green House"
    },
    {
      "mfgId": "INF",
      "mfgName": "Infineon"
    },
    {
      "mfgId": "HAM",
      "mfgName": "Hamilton Sunstrand"
    },
    {
      "mfgId": "INT",
      "mfgName": "Intel"
    },
    {
      "mfgId": "HAR",
      "mfgName": "Harris"
    },
    {
      "mfgId": "IRF",
      "mfgName": "International Rectifier"
    },
    {
      "mfgId": "HTT",
      "mfgName": "Hittite"
    },
    {
      "mfgId": "ISL",
      "mfgName": "Intersil"
    },
    {
      "mfgId": "IAR",
      "mfgName": "IAR Systems"
    },
    {
      "mfgId": "IXY",
      "mfgName": "Ixys"
    },
    {
      "mfgId": "IDE",
      "mfgName": "IDEXX Laboratories"
    },
    {
      "mfgId": "KEM",
      "mfgName": "KEMET"
    },
    {
      "mfgId": "ILC",
      "mfgName": "Illinois Capacitor, INC"
    },
    {
      "mfgId": "KAD",
      "mfgName": "Kidde Aerospace"
    },
    {
      "mfgId": "ISS",
      "mfgName": "Integrated Silicon Solution, Inc."
    },
    {
      "mfgId": "KYO",
      "mfgName": "KYOEI SANGYO"
    },
    {
      "mfgId": "IRC",
      "mfgName": "INTEL RESALE CORP"
    },
    {
      "mfgId": "LAN",
      "mfgName": "Lantiq"
    },
    {
      "mfgId": "IRS",
      "mfgName": "International Resistive Company"
    },
    {
      "mfgId": "LEV",
      "mfgName": "Level One"
    },
    {
      "mfgId": "ITW",
      "mfgName": "ITW Pancon"
    },
    {
      "mfgId": "LFN",
      "mfgName": "Linfinity"
    },
    {
      "mfgId": "KEL",
      "mfgName": "Keil"
    },
    {
      "mfgId": "LSI",
      "mfgName": "LSI Corp."
    },
    {
      "mfgId": "KEN",
      "mfgName": "Kendin"
    },
    {
      "mfgId": "LMN",
      "mfgName": "Luminary Micro"
    },
    {
      "mfgId": "KSE",
      "mfgName": "KOA Speer Electronics"
    },
    {
      "mfgId": "MAX",
      "mfgName": "Maxim"
    },
    {
      "mfgId": "LCO",
      "mfgName": "L-Com"
    },
    {
      "mfgId": "MER",
      "mfgName": "Mercury International"
    },
    {
      "mfgId": "LAT",
      "mfgName": "Lattice"
    },
    {
      "mfgId": "MCL",
      "mfgName": "Micrel"
    },
    {
      "mfgId": "LIN",
      "mfgName": "Linear Technology"
    },
    {
      "mfgId": "MSC",
      "mfgName": "Micro Semi"
    },
    {
      "mfgId": "LLF",
      "mfgName": "Littlefuse"
    },
    {
      "mfgId": "MLC",
      "mfgName": "MicroLinear"
    },
    {
      "mfgId": "LUC",
      "mfgName": "Lucent"
    },
    {
      "mfgId": "MSM",
      "mfgName": "Minisystems"
    },
    {
      "mfgId": "MLY",
      "mfgName": "Mallory"
    },
    {
      "mfgId": "MIT",
      "mfgName": "MITSUBISHI"
    },
    {
      "mfgId": "MST",
      "mfgName": "MDI Star Tell"
    },
    {
      "mfgId": "MOE",
      "mfgName": "Moeller"
    },
    {
      "mfgId": "MGE",
      "mfgName": "MG Electronics"
    },
    {
      "mfgId": "MOT",
      "mfgName": "Motorola"
    },
    {
      "mfgId": "MCC",
      "mfgName": "Micro Crystal"
    },
    {
      "mfgId": "NEC",
      "mfgName": "NEC Corporation"
    },
    {
      "mfgId": "MIC",
      "mfgName": "Microchip"
    },
    {
      "mfgId": "NCC",
      "mfgName": "NIC Components Corp"
    },
    {
      "mfgId": "MCN",
      "mfgName": "Micron"
    },
    {
      "mfgId": "NIC",
      "mfgName": "Nicomatic"
    },
    {
      "mfgId": "MIN",
      "mfgName": "Mintech"
    },
    {
      "mfgId": "NOR",
      "mfgName": "Northrop Grumman"
    },
    {
      "mfgId": "MMI",
      "mfgName": "MMI"
    },
    {
      "mfgId": "NUM",
      "mfgName": "Numonyx"
    },
    {
      "mfgId": "MOL",
      "mfgName": "MOLEX"
    },
    {
      "mfgId": "OHM",
      "mfgName": "OHM Craft"
    },
    {
      "mfgId": "NSC",
      "mfgName": "National Semiconductor"
    },
    {
      "mfgId": "OSC",
      "mfgName": "Oscilent Corporation"
    },
    {
      "mfgId": "NGX",
      "mfgName": "NGX Technologies"
    },
    {
      "mfgId": "PAN",
      "mfgName": "Panasonic"
    },
    {
      "mfgId": "NCN",
      "mfgName": "Nichicon"
    },
    {
      "mfgId": "PSC",
      "mfgName": "Performance Semiconductor Corporation"
    },
    {
      "mfgId": "NAS",
      "mfgName": "North American Specialty"
    },
    {
      "mfgId": "PHI",
      "mfgName": "Philips"
    },
    {
      "mfgId": "NSK",
      "mfgName": "NSK Corporation"
    },
    {
      "mfgId": "PGL",
      "mfgName": "Phoenix Geophysics Ltd."
    },
    {
      "mfgId": "NXP",
      "mfgName": "NXP Semiconductor"
    },
    {
      "mfgId": "PIT",
      "mfgName": "Pitney Bowes"
    },
    {
      "mfgId": "ONS",
      "mfgName": "ON Semiconductor"
    },
    {
      "mfgId": "PII",
      "mfgName": "Positronic Industries, INC."
    },
    {
      "mfgId": "OSR",
      "mfgName": "Osram Opto Semiconductors"
    },
    {
      "mfgId": "PDS",
      "mfgName": "Preci-Dip S.A."
    },
    {
      "mfgId": "PEM",
      "mfgName": "PEM Fastening Systems"
    },
    {
      "mfgId": "QTH",
      "mfgName": "Q-Tech"
    },
    {
      "mfgId": "PER",
      "mfgName": "Pericom"
    },
    {
      "mfgId": "QLG",
      "mfgName": "QuickLogic"
    },
    {
      "mfgId": "PHC",
      "mfgName": "Phoenix Contact"
    },
    {
      "mfgId": "RCH",
      "mfgName": "Raychem"
    },
    {
      "mfgId": "PIL",
      "mfgName": "Pillar Data Systems"
    },
    {
      "mfgId": "RCA",
      "mfgName": "RCA"
    },
    {
      "mfgId": "PMA",
      "mfgName": "PMC-Sierra"
    },
    {
      "mfgId": "REN",
      "mfgName": "Renco Encoders"
    },
    {
      "mfgId": "POW",
      "mfgName": "Power Trends"
    },
    {
      "mfgId": "RFM",
      "mfgName": "RF Micro Devices"
    },
    {
      "mfgId": "PSS",
      "mfgName": "PSC Scanning"
    },
    {
      "mfgId": "REI",
      "mfgName": "Rochester Electronics"
    },
    {
      "mfgId": "QSI",
      "mfgName": "Quality Semiconductor"
    },
    {
      "mfgId": "ROH",
      "mfgName": "ROHM Semiconductor"
    },
    {
      "mfgId": "RAM",
      "mfgName": "Ramtron"
    },
    {
      "mfgId": "SMT",
      "mfgName": "Samtec"
    },
    {
      "mfgId": "RAY",
      "mfgName": "Raytheon Storage"
    },
    {
      "mfgId": "SNY",
      "mfgName": "Sanyo"
    },
    {
      "mfgId": "RCD",
      "mfgName": "RCD Components, Inc"
    },
    {
      "mfgId": "SCH",
      "mfgName": "SCHNEIDER ELECTRIC"
    },
    {
      "mfgId": "RNS",
      "mfgName": "Renesas"
    },
    {
      "mfgId": "SEI",
      "mfgName": "SEI Stackpole Electronics"
    },
    {
      "mfgId": "RIC",
      "mfgName": "Richco Inc."
    },
    {
      "mfgId": "SEM",
      "mfgName": "Semicon Components"
    },
    {
      "mfgId": "ROC",
      "mfgName": "Rockwell Automation"
    },
    {
      "mfgId": "SET",
      "mfgName": "Semtech Int'l AG"
    },
    {
      "mfgId": "SAM",
      "mfgName": "Samsung"
    },
    {
      "mfgId": "SHP",
      "mfgName": "Sharp"
    },
    {
      "mfgId": "SAN",
      "mfgName": "Sandisk"
    },
    {
      "mfgId": "SIG",
      "mfgName": "Sigmatel"
    },
    {
      "mfgId": "SAR",
      "mfgName": "Sarnex"
    },
    {
      "mfgId": "SIM",
      "mfgName": "Simtek"
    },
    {
      "mfgId": "SCT",
      "mfgName": "Schurter"
    },
    {
      "mfgId": "SIT",
      "mfgName": "SiTime"
    },
    {
      "mfgId": "SML",
      "mfgName": "Semelab LTD"
    },
    {
      "mfgId": "SMD",
      "mfgName": "Smart Modular Technologies"
    },
    {
      "mfgId": "SMT",
      "mfgName": "Semitronics"
    },
    {
      "mfgId": "SOL",
      "mfgName": "Solid State"
    },
    {
      "mfgId": "SNT",
      "mfgName": "Sensitron"
    },
    {
      "mfgId": "SPA",
      "mfgName": "Spansion"
    },
    {
      "mfgId": "SIE",
      "mfgName": "Siemens"
    },
    {
      "mfgId": "SST",
      "mfgName": "SST MICRO"
    },
    {
      "mfgId": "SIL",
      "mfgName": "Siliconix"
    },
    {
      "mfgId": "SCS",
      "mfgName": "Stanley Convergent Security Solutions"
    },
    {
      "mfgId": "SIP",
      "mfgName": "Sipex"
    },
    {
      "mfgId": "SYR",
      "mfgName": "Syfer"
    },
    {
      "mfgId": "SLL",
      "mfgName": "Sloan LED"
    },
    {
      "mfgId": "TAK",
      "mfgName": "Takebishi"
    },
    {
      "mfgId": "SMC",
      "mfgName": "SMSC"
    },
    {
      "mfgId": "TEL",
      "mfgName": "Teledyne"
    },
    {
      "mfgId": "SNY",
      "mfgName": "Sony"
    },
    {
      "mfgId": "TIS",
      "mfgName": "Texas Instruments"
    },
    {
      "mfgId": "SPR",
      "mfgName": "Sprague"
    },
    {
      "mfgId": "TOS",
      "mfgName": "Toshiba"
    },
    {
      "mfgId": "STM",
      "mfgName": "ST MICRO"
    },
    {
      "mfgId": "TRI",
      "mfgName": "Triscend"
    },
    {
      "mfgId": "SUE",
      "mfgName": "Sunonwealth Electric"
    },
    {
      "mfgId": "TTE",
      "mfgName": "TT Electronics IRC"
    },
    {
      "mfgId": "TAC",
      "mfgName": "Tachibana Eletech"
    },
    {
      "mfgId": "TYC",
      "mfgName": "Tyco"
    },
    {
      "mfgId": "TMS",
      "mfgName": "Tekmos"
    },
    {
      "mfgId": "USM",
      "mfgName": "Unisem"
    },
    {
      "mfgId": "TLE",
      "mfgName": "Telemecanique"
    },
    {
      "mfgId": "UNI",
      "mfgName": "Unitrode"
    },
    {
      "mfgId": "TFP",
      "mfgName": "Thai First Precision Ind. Co., LTD."
    },
    {
      "mfgId": "VNC",
      "mfgName": "Vernitron Corporation"
    },
    {
      "mfgId": "TSE",
      "mfgName": "Tri-Star Electronics, Inc."
    },
    {
      "mfgId": "WFE",
      "mfgName": "Wakefield Solutions"
    },
    {
      "mfgId": "TEI",
      "mfgName": "Trompeter Electronics, INC."
    },
    {
      "mfgId": "WEI",
      "mfgName": "Weikeng Industrial"
    },
    {
      "mfgId": "TTI",
      "mfgName": "TTI"
    },
    {
      "mfgId": "WED",
      "mfgName": "White Electronic Design"
    },
    {
      "mfgId": "TYC",
      "mfgName": "Tyco Healthcare"
    },
    {
      "mfgId": "XCR",
      "mfgName": "Xicor"
    },
    {
      "mfgId": "UMC",
      "mfgName": "United Microelectronics Corporation"
    },
    {
      "mfgId": "XTS",
      "mfgName": "XTREME Semiconductor"
    },
    {
      "mfgId": "VAN",
      "mfgName": "Vantis"
    },
    {
      "mfgId": "YCL",
      "mfgName": "YCL Electronics Co."
    },
    {
      "mfgId": "VIS",
      "mfgName": "VISHAY"
    },
    {
      "mfgId": "ZLG",
      "mfgName": "Zilog"
    },
    {
      "mfgId": "WEC",
      "mfgName": "Weco"
    },
    {
      "mfgId": "WEL",
      "mfgName": "Welwyn"
    },
    {
      "mfgId": "WEM",
      "mfgName": "Wurth Elektronik Midcom"
    },
    {
      "mfgId": "XLX",
      "mfgName": "Xilinx"
    },
    {
      "mfgId": "YAG",
      "mfgName": "Yageo"
    },
    {
      "mfgId": "ZAR",
      "mfgName": "Zarlink"
    }
  ]
}